#!/usr/bin/env node
// Regenerates src/data/cheeses.ts and src/data/fr-map.ts from a design
// handoff folder's cheeses.js / fr-map.js (window.CHEESES / window.FR_XY).
//
// Usage: node scripts/import-cheeses.mjs [--handoff <dir>] [--region <id>] [--region-name <name>]
//
// Run this again whenever a new region's handoff folder needs to be merged
// in: point --handoff at the new folder and pass a new --region/--region-name,
// then hand-merge the emitted array into src/data/cheeses.ts (each region's
// cheeses keep their own regionId, so nothing needs to be renamed).

import fs from 'node:fs'
import path from 'node:path'
import vm from 'node:vm'
import url from 'node:url'

const __dirname = path.dirname(url.fileURLToPath(import.meta.url))
const repoRoot = path.resolve(__dirname, '..')

function parseArgs(argv) {
  const args = { handoff: path.resolve(repoRoot, '../design_handoff_fromages_france'), region: 'auvergne-rhone-alpes', regionName: 'Auvergne-Rhône-Alpes' }
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === '--handoff') args.handoff = path.resolve(argv[++i])
    else if (argv[i] === '--region') args.region = argv[++i]
    else if (argv[i] === '--region-name') args.regionName = argv[++i]
  }
  return args
}

function loadWindowScript(filePath) {
  const code = fs.readFileSync(filePath, 'utf8')
  const sandbox = { window: {} }
  vm.createContext(sandbox)
  vm.runInContext(code, sandbox, { filename: filePath })
  return sandbox.window
}

function main() {
  const { handoff, region, regionName } = parseArgs(process.argv.slice(2))

  const cheesesWindow = loadWindowScript(path.join(handoff, 'cheeses.js'))
  const mapWindow = loadWindowScript(path.join(handoff, 'fr-map.js'))

  const cheeses = (cheesesWindow.CHEESES || []).map((c) => ({ ...c, regionId: region }))
  const frXY = mapWindow.FR_XY || {}

  const cheesesOut = `// GENERATED by scripts/import-cheeses.mjs from ${path.relative(repoRoot, path.join(handoff, 'cheeses.js'))}
// Do not hand-edit — rerun the import script to regenerate.
import type { Cheese } from './cheese.types'

export const CHEESES: Cheese[] = ${JSON.stringify(cheeses, null, 2)}
`

  const frMapOut = `// GENERATED by scripts/import-cheeses.mjs from ${path.relative(repoRoot, path.join(handoff, 'fr-map.js'))}
// Real projected coordinates (viewBox 0 0 100 100) of each cheese on the
// metropolitan France outline, from Natural Earth data via d3-geo.
// Do not hand-edit — rerun the import script to regenerate.
export const FR_XY: Record<string, [number, number]> = ${JSON.stringify(frXY, null, 2)}
`

  fs.writeFileSync(path.join(repoRoot, 'src/data/cheeses.ts'), cheesesOut)
  fs.writeFileSync(path.join(repoRoot, 'src/data/fr-map.ts'), frMapOut)

  const regionsPath = path.join(repoRoot, 'src/data/regions.ts')
  if (!fs.existsSync(regionsPath)) {
    fs.writeFileSync(
      regionsPath,
      `import type { Region } from './cheese.types'\n\nexport const REGIONS: Region[] = [\n  { id: '${region}', name: '${regionName}' },\n]\n`,
    )
  }

  console.log(`Wrote ${cheeses.length} cheeses (region "${region}") to src/data/cheeses.ts`)
  console.log(`Wrote ${Object.keys(frXY).length} map coordinates to src/data/fr-map.ts`)
}

main()
