// GENERATED by scripts/import-cheeses.mjs from ../design_handoff_fromages_france/cheeses.js
// Do not hand-edit — rerun the import script to regenerate.
import type { Cheese } from './cheese.types'

export const CHEESES: Cheese[] = [
  {
    "id": "reblochon",
    "nom": "Reblochon",
    "alt": [
      "Reblochon de Savoie"
    ],
    "dept": "Haute-Savoie (74)",
    "commune": "Vallée de Thônes",
    "lait": "Vache",
    "race": "Abondance, Tarine, Montbéliarde",
    "famille": "Pâte pressée non cuite",
    "croute": "Lavée, fine, safranée",
    "texture": "Souple et fondante",
    "forme": "Disque plat",
    "poids": "450–550 g",
    "dim": "Ø 14 cm · 3,5 cm",
    "affinage": "6–8 semaines",
    "mg": "50 %",
    "saison": "Été → Hiver",
    "intensite": 3,
    "aop": true,
    "prix": "≈ 28 €/kg",
    "dispo": "Courante",
    "color": "Ivoire à jaune paille",
    "notes": [
      "Noisette",
      "Crème fraîche",
      "Sous-bois",
      "Beurre"
    ],
    "accords": {
      "vin": "Vin de Savoie (Apremont, Roussette)",
      "biere": "Blonde légère de montagne",
      "cidre": "Cidre brut fermier",
      "whisky": "Single malt doux des Highlands",
      "pain": "Pain de seigle, pain aux noix"
    },
    "histoire": "Né au XIIIᵉ siècle dans les alpages de Thônes : les fermiers pratiquaient la « rebloche », une seconde traite discrète effectuée après le passage du contrôleur seigneurial. Ce lait plus riche donnait un fromage crémeux réservé à la famille.",
    "anecdote": "Le nom vient du patois savoyard « re-blocher » : pincer à nouveau le pis de la vache.",
    "fabrication": "Lait cru emprésuré, caillé découpé puis pressé légèrement en moule. Affinage sur planche d'épicéa, croûte lavée à l'eau salée.",
    "conservation": "Bac à légumes du réfrigérateur, dans son papier d'origine, 8–10 jours.",
    "service": "À température ambiante 1 h avant dégustation ; cœur de la tartiflette.",
    "nutrition": {
      "energie": "330 kcal",
      "proteines": "20 g",
      "lipides": "27 g",
      "calcium": "500 mg"
    },
    "galerie": [
      "Vue entière",
      "Coupe",
      "Croûte lavée",
      "Plateau",
      "Cave d'affinage"
    ],
    "map": [
      82,
      66
    ],
    "regionId": "auvergne-rhone-alpes"
  },
  {
    "id": "beaufort",
    "nom": "Beaufort",
    "alt": [
      "Prince des gruyères"
    ],
    "dept": "Savoie (73)",
    "commune": "Beaufortain, Tarentaise",
    "lait": "Vache",
    "race": "Tarine, Abondance",
    "famille": "Pâte pressée cuite",
    "croute": "Frottée, jaune à brune",
    "texture": "Ferme, fondante, sans trou",
    "forme": "Meule à talon concave",
    "poids": "20–70 kg",
    "dim": "Ø 35–75 cm",
    "affinage": "5 mois → 2 ans",
    "mg": "48 %",
    "saison": "Toute l'année",
    "intensite": 4,
    "aop": true,
    "prix": "≈ 34 €/kg",
    "dispo": "Courante",
    "color": "Jaune doré",
    "notes": [
      "Fruité",
      "Beurre noisette",
      "Fleurs de montagne",
      "Grillé"
    ],
    "accords": {
      "vin": "Roussette de Savoie, Chardonnay du Jura",
      "biere": "Ambrée de dégustation",
      "cidre": "Cidre demi-sec",
      "whisky": "Speyside fruité et miellé",
      "pain": "Pain de campagne au levain"
    },
    "histoire": "Fromage de garde des alpages de Tarentaise, façonné pour traverser l'hiver. Le talon concave épouse le cercle de bois « beaufort » qui lui a donné son nom.",
    "anecdote": "Le Beaufort « chalet d'alpage » est fabriqué au-dessus de 1500 m, deux fois par jour, avec le lait d'un seul troupeau.",
    "fabrication": "Lait cru chauffé à 53 °C, caillé pressé fortement dans la toile de lin puis le cercle de bois.",
    "conservation": "Réfrigérateur 3–4 semaines, emballé dans un linge légèrement humide.",
    "service": "En copeaux à l'apéritif, en fondue, ou en fin de repas avec des fruits secs.",
    "nutrition": {
      "energie": "401 kcal",
      "proteines": "26 g",
      "lipides": "33 g",
      "calcium": "1000 mg"
    },
    "galerie": [
      "Meule entière",
      "Coupe",
      "Talon concave",
      "Plateau",
      "Cave d'affinage"
    ],
    "map": [
      84,
      70
    ],
    "regionId": "auvergne-rhone-alpes"
  },
  {
    "id": "bleu-auvergne",
    "nom": "Bleu d'Auvergne",
    "alt": [],
    "dept": "Cantal / Puy-de-Dôme (15/63)",
    "commune": "Massif central",
    "lait": "Vache",
    "race": "Salers, Montbéliarde",
    "famille": "Pâte persillée",
    "croute": "Naturelle, fleurie et fine",
    "texture": "Onctueuse, persillée",
    "forme": "Cylindre",
    "poids": "2–3 kg",
    "dim": "Ø 20 cm · 10 cm",
    "affinage": "4 semaines minimum",
    "mg": "50 %",
    "saison": "Printemps → Automne",
    "intensite": 4,
    "aop": true,
    "prix": "≈ 22 €/kg",
    "dispo": "Courante",
    "color": "Ivoire veiné de bleu-vert",
    "notes": [
      "Champignon",
      "Sous-bois",
      "Épices",
      "Beurre salé"
    ],
    "accords": {
      "vin": "Vin doux naturel (Maury, Banyuls)",
      "biere": "Stout impérial",
      "cidre": "Cidre doux",
      "whisky": "Islay tourbé",
      "pain": "Pain aux figues, pain de seigle"
    },
    "histoire": "Inventé au milieu du XIXᵉ siècle par un fermier d'Auvergne qui ensemença son caillé de moisissure de pain de seigle, puis perça la pâte pour aérer le bleu.",
    "anecdote": "Ce sont les aiguilles de piquage qui laissent entrer l'air, permettant au Penicillium de se développer en veines régulières.",
    "fabrication": "Caillé ensemencé au Penicillium roqueforti, moulé sans presser, salé puis piqué.",
    "conservation": "Réfrigérateur, sous papier alu, 2–3 semaines.",
    "service": "À température ambiante, émietté sur une salade ou fondu en sauce.",
    "nutrition": {
      "energie": "354 kcal",
      "proteines": "19 g",
      "lipides": "30 g",
      "calcium": "550 mg"
    },
    "galerie": [
      "Vue entière",
      "Coupe persillée",
      "Intérieur",
      "Plateau",
      "Cave"
    ],
    "map": [
      55,
      62
    ],
    "regionId": "auvergne-rhone-alpes"
  },
  {
    "id": "saint-nectaire",
    "nom": "Saint-Nectaire",
    "alt": [],
    "dept": "Puy-de-Dôme / Cantal (63/15)",
    "commune": "Massif du Sancy",
    "lait": "Vache",
    "race": "Salers, Ferrandaise",
    "famille": "Pâte pressée non cuite",
    "croute": "Naturelle fleurie, grise à orangée",
    "texture": "Souple, moelleuse",
    "forme": "Disque plat",
    "poids": "1,7 kg",
    "dim": "Ø 21 cm · 5 cm",
    "affinage": "5–8 semaines sur paille de seigle",
    "mg": "45 %",
    "saison": "Été → Automne",
    "intensite": 3,
    "aop": true,
    "prix": "≈ 24 €/kg",
    "dispo": "Courante",
    "color": "Jaune paille",
    "notes": [
      "Sous-bois",
      "Champignon frais",
      "Noisette",
      "Terroir volcanique"
    ],
    "accords": {
      "vin": "Côtes d'Auvergne rouge, Saint-Pourçain",
      "biere": "Brune de garde",
      "cidre": "Cidre brut",
      "whisky": "Highlands rond",
      "pain": "Pain de campagne, seigle"
    },
    "histoire": "Cité à la table de Louis XIV par le maréchal de Senneterre, dont le nom francisé a baptisé le fromage. Affiné sur de la paille de seigle qui lui donne ses arômes de cave.",
    "anecdote": "La croûte se pare de moisissures « fleurs » blanches, jaunes et rouges, signature de l'affinage sur paille.",
    "fabrication": "Lait cru pressé, salé, affiné en cave humide sur paille de seigle.",
    "conservation": "Bac du réfrigérateur, papier d'origine, 1–2 semaines.",
    "service": "Sur un plateau, ou fondu sur des pommes de terre.",
    "nutrition": {
      "energie": "338 kcal",
      "proteines": "20 g",
      "lipides": "28 g",
      "calcium": "560 mg"
    },
    "galerie": [
      "Vue entière",
      "Coupe",
      "Croûte fleurie",
      "Plateau",
      "Cave sur paille"
    ],
    "map": [
      54,
      60
    ],
    "regionId": "auvergne-rhone-alpes"
  },
  {
    "id": "fourme-ambert",
    "nom": "Fourme d'Ambert",
    "alt": [
      "Fourme de Pierre-sur-Haute"
    ],
    "dept": "Puy-de-Dôme (63)",
    "commune": "Monts du Forez",
    "lait": "Vache",
    "race": "Montbéliarde, Prim'Holstein",
    "famille": "Pâte persillée",
    "croute": "Naturelle grise, sèche",
    "texture": "Fine, crémeuse, persillée",
    "forme": "Haut cylindre",
    "poids": "≈ 2 kg",
    "dim": "Ø 13 cm · 19 cm",
    "affinage": "4 semaines minimum",
    "mg": "50 %",
    "saison": "Toute l'année",
    "intensite": 3,
    "aop": true,
    "prix": "≈ 21 €/kg",
    "dispo": "Courante",
    "color": "Ivoire veiné de bleu",
    "notes": [
      "Doux",
      "Beurre",
      "Champignon",
      "Fruits secs"
    ],
    "accords": {
      "vin": "Sauternes, vin de paille",
      "biere": "Blonde d'abbaye",
      "cidre": "Cidre doux",
      "whisky": "Speyside sherry",
      "pain": "Pain aux noix, brioche"
    },
    "histoire": "L'un des plus anciens bleus de France, sa haute silhouette cylindrique remonterait à l'époque gallo-romaine dans les jasseries des monts du Forez.",
    "anecdote": "C'est l'un des bleus les plus doux : parfait pour découvrir les pâtes persillées.",
    "fabrication": "Caillé ensemencé, moulé en haute forme, piqué pour le persillage.",
    "conservation": "Réfrigérateur, alu, 2–3 semaines.",
    "service": "En cube à l'apéritif, ou en sauce pour les viandes.",
    "nutrition": {
      "energie": "350 kcal",
      "proteines": "20 g",
      "lipides": "29 g",
      "calcium": "540 mg"
    },
    "galerie": [
      "Cylindre entier",
      "Coupe persillée",
      "Intérieur",
      "Plateau",
      "Cave"
    ],
    "map": [
      58,
      58
    ],
    "regionId": "auvergne-rhone-alpes"
  },
  {
    "id": "cantal",
    "nom": "Cantal",
    "alt": [
      "Fourme de Cantal"
    ],
    "dept": "Cantal (15)",
    "commune": "Monts du Cantal",
    "lait": "Vache",
    "race": "Salers",
    "famille": "Pâte pressée non cuite",
    "croute": "Sèche, dorée à grise",
    "texture": "Ferme, friable puis fondante",
    "forme": "Fourme cylindrique",
    "poids": "35–45 kg",
    "dim": "Ø 40 cm",
    "affinage": "Jeune 1 mois · Entre-deux · Vieux 8 mois+",
    "mg": "45 %",
    "saison": "Toute l'année",
    "intensite": 3,
    "aop": true,
    "prix": "≈ 20 €/kg",
    "dispo": "Courante",
    "color": "Jaune ivoire",
    "notes": [
      "Lactique",
      "Noisette",
      "Beurre",
      "Piquant (vieux)"
    ],
    "accords": {
      "vin": "Marcillac, Côtes d'Auvergne",
      "biere": "Ambrée",
      "cidre": "Cidre brut",
      "whisky": "Highlands",
      "pain": "Pain de seigle"
    },
    "histoire": "L'un des plus vieux fromages d'Europe, décrit par Pline l'Ancien il y a 2000 ans. Le lait est pressé deux fois pour former la « tome » avant le moulage.",
    "anecdote": "La tome fraîche de Cantal non affinée sert à l'aligot et à la truffade.",
    "fabrication": "Caillé pressé, broyé en tome, salé, repressé en fourme puis affiné.",
    "conservation": "Réfrigérateur 2–3 semaines.",
    "service": "En bâtonnets, râpé, ou en aligot.",
    "nutrition": {
      "energie": "390 kcal",
      "proteines": "23 g",
      "lipides": "32 g",
      "calcium": "700 mg"
    },
    "galerie": [
      "Fourme entière",
      "Coupe",
      "Talon",
      "Plateau",
      "Cave"
    ],
    "map": [
      52,
      62
    ],
    "regionId": "auvergne-rhone-alpes"
  },
  {
    "id": "picodon",
    "nom": "Picodon",
    "alt": [
      "Picodon de la Drôme"
    ],
    "dept": "Drôme / Ardèche (26/07)",
    "commune": "Vallée du Rhône",
    "lait": "Chèvre",
    "race": "Alpine, Saanen",
    "famille": "Pâte molle à croûte naturelle",
    "croute": "Naturelle, fleurie",
    "texture": "Ferme à sèche selon l'affinage",
    "forme": "Petit palet",
    "poids": "45–60 g",
    "dim": "Ø 5–7 cm",
    "affinage": "12 jours → 1 mois+",
    "mg": "45 %",
    "saison": "Printemps → Automne",
    "intensite": 3,
    "aop": true,
    "prix": "≈ 32 €/kg",
    "dispo": "Saisonnière",
    "color": "Blanc à ivoire",
    "notes": [
      "Caprin",
      "Noisette",
      "Épicé (affiné)",
      "Fleurs sèches"
    ],
    "accords": {
      "vin": "Côtes du Rhône blanc, Clairette de Die",
      "biere": "Blanche",
      "cidre": "Cidre sec",
      "whisky": "Lowlands léger",
      "pain": "Fougasse, pain aux herbes"
    },
    "histoire": "Fromage de garde des paysans du Dauphiné et du Vivarais. Son nom vient de l'occitan « picaou » : piquant, pour l'affiné relevé.",
    "anecdote": "Le « Picodon méthode Dieulefit » est lavé et affiné plus longtemps, jusqu'à devenir sec et cassant.",
    "fabrication": "Caillé lactique moulé à la louche, égoutté, salé, séché et affiné.",
    "conservation": "Réfrigérateur, boîte aérée, 1–2 semaines.",
    "service": "Frais sur salade, ou affiné avec un filet d'huile d'olive.",
    "nutrition": {
      "energie": "290 kcal",
      "proteines": "18 g",
      "lipides": "23 g",
      "calcium": "140 mg"
    },
    "galerie": [
      "Palets entiers",
      "Coupe",
      "Croûte fleurie",
      "Plateau",
      "Séchoir"
    ],
    "map": [
      66,
      68
    ],
    "regionId": "auvergne-rhone-alpes"
  },
  {
    "id": "mont-dor",
    "nom": "Mont d'Or",
    "alt": [
      "Vacherin du Haut-Doubs"
    ],
    "dept": "Doubs / Haute-Savoie (25/74)",
    "commune": "Massif du Mont d'Or",
    "lait": "Vache",
    "race": "Montbéliarde",
    "famille": "Pâte molle à croûte lavée",
    "croute": "Lavée, plissée, jaune-orangé",
    "texture": "Coulante, à la cuillère",
    "forme": "Disque en boîte d'épicéa",
    "poids": "480 g – 3,2 kg",
    "dim": "Ø 11–33 cm",
    "affinage": "3 semaines minimum",
    "mg": "45 %",
    "saison": "Automne → Hiver (15 août – 15 mars)",
    "intensite": 3,
    "aop": true,
    "prix": "≈ 30 €/kg",
    "dispo": "Saisonnière",
    "color": "Ivoire crémeux",
    "notes": [
      "Résine d'épicéa",
      "Crème",
      "Sous-bois",
      "Bois"
    ],
    "accords": {
      "vin": "Vin jaune du Jura, Savagnin",
      "biere": "Blonde d'hiver",
      "cidre": "Cidre demi-sec",
      "whisky": "Highlands boisé",
      "pain": "Pain de campagne, pommes de terre"
    },
    "histoire": "Fromage d'hiver sanglé d'une écorce d'épicéa qui le parfume et le tient. On le déguste traditionnellement chaud, la « boîte chaude », cuit au four.",
    "anecdote": "Sa saison est strictement délimitée : de mi-août à mi-mars, quand les vaches sont à l'étable.",
    "fabrication": "Lait cru moulé, sanglé d'écorce d'épicéa, croûte lavée régulièrement.",
    "conservation": "Réfrigérateur, dans sa boîte, jusqu'à la DLC ; consommer vite une fois ouvert.",
    "service": "À la cuillère, ou chaud au four « boîte chaude » avec ail et vin blanc.",
    "nutrition": {
      "energie": "300 kcal",
      "proteines": "16 g",
      "lipides": "26 g",
      "calcium": "450 mg"
    },
    "galerie": [
      "Boîte entière",
      "Cœur coulant",
      "Croûte plissée",
      "Boîte chaude",
      "Cave"
    ],
    "map": [
      80,
      52
    ],
    "regionId": "auvergne-rhone-alpes"
  },
  {
    "id": "brillat-savarin",
    "nom": "Brillat-Savarin",
    "alt": [
      "Le roi des fromages triple-crème"
    ],
    "dept": "Ain (01) / Bourgogne",
    "commune": "Bresse",
    "lait": "Vache",
    "race": "Prim'Holstein",
    "famille": "Pâte molle triple-crème",
    "croute": "Fleurie, blanche et duveteuse",
    "texture": "Ultra-crémeuse, beurrée",
    "forme": "Petit cylindre",
    "poids": "200–500 g",
    "dim": "Ø 12 cm",
    "affinage": "1–2 semaines",
    "mg": "72 % (triple-crème)",
    "saison": "Toute l'année",
    "intensite": 2,
    "aop": false,
    "prix": "≈ 26 €/kg",
    "dispo": "Courante",
    "color": "Blanc ivoire",
    "notes": [
      "Beurre",
      "Crème fraîche",
      "Champignon de Paris",
      "Amande"
    ],
    "accords": {
      "vin": "Champagne, Crémant de Bourgogne",
      "biere": "Blanche fruitée",
      "cidre": "Cidre bouché brut",
      "whisky": "Lowlands délicat",
      "pain": "Baguette tradition, brioche"
    },
    "histoire": "Créé au XXᵉ siècle par la maison Dubuc puis popularisé par Henri Androuët, nommé en hommage au gastronome Jean Anthelme Brillat-Savarin.",
    "anecdote": "Enrichi de crème, il titre plus de 72 % de matière grasse : un vrai fromage-dessert.",
    "fabrication": "Lait additionné de crème, caillage lent, moulage délicat, courte maturation.",
    "conservation": "Réfrigérateur, 1 semaine.",
    "service": "Nature, avec des fruits rouges, ou façon cheesecake.",
    "nutrition": {
      "energie": "410 kcal",
      "proteines": "12 g",
      "lipides": "40 g",
      "calcium": "300 mg"
    },
    "galerie": [
      "Vue entière",
      "Coupe crémeuse",
      "Croûte fleurie",
      "Plateau",
      "Cave"
    ],
    "map": [
      72,
      52
    ],
    "regionId": "auvergne-rhone-alpes"
  },
  {
    "id": "rigotte-condrieu",
    "nom": "Rigotte de Condrieu",
    "alt": [],
    "dept": "Rhône / Loire (69/42)",
    "commune": "Massif du Pilat",
    "lait": "Chèvre",
    "race": "Alpine",
    "famille": "Pâte molle à croûte naturelle",
    "croute": "Naturelle, fleurie bleutée",
    "texture": "Fondante puis ferme",
    "forme": "Petit palet bombé",
    "poids": "30–70 g",
    "dim": "Ø 4–5 cm",
    "affinage": "8 jours → 1 mois",
    "mg": "45 %",
    "saison": "Printemps → Automne",
    "intensite": 2,
    "aop": true,
    "prix": "≈ 40 €/kg",
    "dispo": "Saisonnière",
    "color": "Ivoire",
    "notes": [
      "Caprin doux",
      "Noisette",
      "Fleurs",
      "Miel"
    ],
    "accords": {
      "vin": "Condrieu (Viognier)",
      "biere": "Blanche",
      "cidre": "Cidre sec",
      "whisky": "Lowlands",
      "pain": "Pain aux céréales"
    },
    "histoire": "Petit fromage des coteaux du Pilat, longtemps vendu sur les marchés de Condrieu. Il accompagne naturellement le grand vin blanc voisin.",
    "anecdote": "Sa croûte se couvre d'un fin duvet bleuté quand il vieillit.",
    "fabrication": "Caillé lactique moulé, égoutté lentement, affiné en cave fraîche.",
    "conservation": "Réfrigérateur, 1 semaine.",
    "service": "Nature, tiède sur toast, ou avec du miel.",
    "nutrition": {
      "energie": "300 kcal",
      "proteines": "19 g",
      "lipides": "24 g",
      "calcium": "150 mg"
    },
    "galerie": [
      "Palets",
      "Coupe",
      "Croûte bleutée",
      "Plateau",
      "Cave"
    ],
    "map": [
      64,
      60
    ],
    "regionId": "auvergne-rhone-alpes"
  },
  {
    "id": "chevrotin",
    "nom": "Chevrotin",
    "alt": [
      "Chevrotin des Aravis"
    ],
    "dept": "Haute-Savoie / Savoie (74/73)",
    "commune": "Massif des Aravis",
    "lait": "Chèvre",
    "race": "Alpine, Chèvre des Savoie",
    "famille": "Pâte pressée non cuite",
    "croute": "Lavée, morge rosée",
    "texture": "Souple, fondante",
    "forme": "Petit disque",
    "poids": "250–350 g",
    "dim": "Ø 9–12 cm",
    "affinage": "3 semaines minimum",
    "mg": "45 %",
    "saison": "Printemps → Automne",
    "intensite": 3,
    "aop": true,
    "prix": "≈ 38 €/kg",
    "dispo": "Saisonnière",
    "color": "Ivoire",
    "notes": [
      "Caprin",
      "Noisette",
      "Sous-bois",
      "Crème"
    ],
    "accords": {
      "vin": "Vin de Savoie blanc",
      "biere": "Ambrée légère",
      "cidre": "Cidre brut",
      "whisky": "Speyside",
      "pain": "Pain de seigle"
    },
    "histoire": "Cousin caprin du Reblochon, fabriqué à la ferme dans les Aravis. Seul chevrotin AOP, il perpétue un savoir-faire fermier ancien.",
    "anecdote": "Exclusivement fermier : chaque Chevrotin est fabriqué au lait cru par le producteur lui-même.",
    "fabrication": "Lait cru de chèvre pressé, croûte lavée à la morge.",
    "conservation": "Réfrigérateur, 1–2 semaines.",
    "service": "Sur un plateau caprin, à température ambiante.",
    "nutrition": {
      "energie": "320 kcal",
      "proteines": "20 g",
      "lipides": "26 g",
      "calcium": "500 mg"
    },
    "galerie": [
      "Vue entière",
      "Coupe",
      "Croûte lavée",
      "Plateau",
      "Cave"
    ],
    "map": [
      83,
      68
    ],
    "regionId": "auvergne-rhone-alpes"
  },
  {
    "id": "abondance",
    "nom": "Abondance",
    "alt": [],
    "dept": "Haute-Savoie (74)",
    "commune": "Vallée d'Abondance",
    "lait": "Vache",
    "race": "Abondance",
    "famille": "Pâte pressée cuite",
    "croute": "Frottée, ambrée",
    "texture": "Ferme, souple, fruitée",
    "forme": "Meule à talon concave",
    "poids": "6–12 kg",
    "dim": "Ø 38–43 cm",
    "affinage": "3 mois minimum",
    "mg": "48 %",
    "saison": "Toute l'année",
    "intensite": 3,
    "aop": true,
    "prix": "≈ 30 €/kg",
    "dispo": "Courante",
    "color": "Ivoire à jaune",
    "notes": [
      "Fruité",
      "Noisette grillée",
      "Beurre",
      "Alpage"
    ],
    "accords": {
      "vin": "Vin de Savoie, Chignin-Bergeron",
      "biere": "Ambrée",
      "cidre": "Cidre demi-sec",
      "whisky": "Highlands",
      "pain": "Pain de campagne"
    },
    "histoire": "Fabriqué depuis le XIIᵉ siècle par les moines de l'abbaye d'Abondance, avec le lait de la race locale du même nom.",
    "anecdote": "En 1381, 1,4 tonne d'Abondance fut livrée pour le conclave d'Avignon.",
    "fabrication": "Lait cru chauffé, pressé en meule à talon concave, affiné 3 mois.",
    "conservation": "Réfrigérateur 3 semaines.",
    "service": "En copeaux, en berthoud (fondu au vin blanc).",
    "nutrition": {
      "energie": "400 kcal",
      "proteines": "25 g",
      "lipides": "33 g",
      "calcium": "900 mg"
    },
    "galerie": [
      "Meule",
      "Coupe",
      "Talon",
      "Plateau",
      "Cave"
    ],
    "map": [
      84,
      64
    ],
    "regionId": "auvergne-rhone-alpes"
  },
  {
    "id": "bleu-gex",
    "nom": "Bleu de Gex",
    "alt": [
      "Bleu du Haut-Jura",
      "Bleu de Septmoncel"
    ],
    "dept": "Ain / Jura (01/39)",
    "commune": "Haut-Jura",
    "lait": "Vache",
    "race": "Montbéliarde",
    "famille": "Pâte persillée",
    "croute": "Naturelle, sèche",
    "texture": "Onctueuse, persillée fine",
    "forme": "Meule plate",
    "poids": "6–9 kg",
    "dim": "Ø 31 cm",
    "affinage": "3 semaines à 1 mois",
    "mg": "50 %",
    "saison": "Toute l'année",
    "intensite": 3,
    "aop": true,
    "prix": "≈ 26 €/kg",
    "dispo": "Courante",
    "color": "Ivoire veiné",
    "notes": [
      "Doux",
      "Noisette",
      "Champignon"
    ],
    "accords": {
      "vin": "Vin jaune du Jura",
      "biere": "Blonde",
      "cidre": "Cidre doux",
      "whisky": "Speyside",
      "pain": "Pain de seigle"
    },
    "histoire": "Introduit au XIVᵉ siècle par des moines venus du Dauphiné dans le Haut-Jura, marqué de la mention « Gex » à la croûte.",
    "nutrition": {
      "energie": "340 kcal",
      "proteines": "20 g",
      "lipides": "28 g",
      "calcium": "540 mg"
    },
    "galerie": [
      "Meule",
      "Coupe",
      "Intérieur",
      "Plateau",
      "Cave"
    ],
    "map": [
      78,
      54
    ],
    "regionId": "auvergne-rhone-alpes"
  },
  {
    "id": "bleu-vercors",
    "nom": "Bleu du Vercors-Sassenage",
    "alt": [],
    "dept": "Isère (38)",
    "commune": "Massif du Vercors",
    "lait": "Vache",
    "race": "Villard-de-Lans, Montbéliarde",
    "famille": "Pâte persillée",
    "croute": "Naturelle fine",
    "texture": "Souple, crémeuse",
    "forme": "Meule plate",
    "poids": "4–4,5 kg",
    "dim": "Ø 27–30 cm",
    "affinage": "3 semaines minimum",
    "mg": "48 %",
    "saison": "Toute l'année",
    "intensite": 2,
    "aop": true,
    "prix": "≈ 24 €/kg",
    "dispo": "Courante",
    "color": "Ivoire veiné de bleu léger",
    "notes": [
      "Très doux",
      "Beurre",
      "Noisette"
    ],
    "accords": {
      "vin": "Clairette de Die",
      "biere": "Blonde",
      "cidre": "Cidre doux",
      "whisky": "Lowlands",
      "pain": "Pain aux noix"
    },
    "histoire": "Fromage du plateau du Vercors mentionné dès le XIVᵉ siècle, l'un des bleus les plus doux de France.",
    "nutrition": {
      "energie": "330 kcal",
      "proteines": "19 g",
      "lipides": "27 g",
      "calcium": "520 mg"
    },
    "galerie": [
      "Meule",
      "Coupe",
      "Intérieur",
      "Plateau",
      "Cave"
    ],
    "map": [
      72,
      66
    ],
    "regionId": "auvergne-rhone-alpes"
  },
  {
    "id": "bleu-causses",
    "nom": "Bleu des Causses",
    "alt": [],
    "dept": "Aveyron (12)",
    "commune": "Causses du Massif central",
    "lait": "Vache",
    "race": "Aubrac, Simmental",
    "famille": "Pâte persillée",
    "croute": "Naturelle humide",
    "texture": "Onctueuse, persillée",
    "forme": "Cylindre",
    "poids": "2,3–3 kg",
    "dim": "Ø 20 cm",
    "affinage": "3–6 mois en caves naturelles",
    "mg": "45 %",
    "saison": "Toute l'année",
    "intensite": 4,
    "aop": true,
    "prix": "≈ 23 €/kg",
    "dispo": "Courante",
    "color": "Ivoire veiné",
    "notes": [
      "Puissant",
      "Beurre",
      "Épices",
      "Cave"
    ],
    "accords": {
      "vin": "Porto, Banyuls",
      "biere": "Stout",
      "cidre": "Cidre doux",
      "whisky": "Islay",
      "pain": "Pain aux fruits secs"
    },
    "histoire": "Affiné dans les « fleurines », failles naturelles des caves calcaires des Causses qui ventilent le fromage.",
    "nutrition": {
      "energie": "355 kcal",
      "proteines": "20 g",
      "lipides": "30 g",
      "calcium": "560 mg"
    },
    "galerie": [
      "Cylindre",
      "Coupe",
      "Intérieur",
      "Plateau",
      "Fleurines"
    ],
    "map": [
      50,
      68
    ],
    "regionId": "auvergne-rhone-alpes"
  },
  {
    "id": "laguiole",
    "nom": "Laguiole",
    "alt": [
      "Fourme de Laguiole"
    ],
    "dept": "Aveyron (12)",
    "commune": "Aubrac",
    "lait": "Vache",
    "race": "Aubrac, Simmental",
    "famille": "Pâte pressée non cuite",
    "croute": "Sèche, épaisse, grise",
    "texture": "Ferme, fondante",
    "forme": "Grande fourme",
    "poids": "20–50 kg",
    "dim": "Ø 40 cm",
    "affinage": "4 mois minimum",
    "mg": "45 %",
    "saison": "Toute l'année",
    "intensite": 4,
    "aop": true,
    "prix": "≈ 28 €/kg",
    "dispo": "Courante",
    "color": "Jaune ivoire",
    "notes": [
      "Fruité puissant",
      "Herbe",
      "Piquant",
      "Beurre"
    ],
    "accords": {
      "vin": "Marcillac, Madiran",
      "biere": "Ambrée",
      "cidre": "Cidre brut",
      "whisky": "Highlands",
      "pain": "Pain de campagne"
    },
    "histoire": "Fabriqué sur les hauts plateaux de l'Aubrac depuis le Moyen Âge par les moines ; base de l'aligot avec la tome fraîche.",
    "nutrition": {
      "energie": "390 kcal",
      "proteines": "24 g",
      "lipides": "32 g",
      "calcium": "700 mg"
    },
    "galerie": [
      "Fourme",
      "Coupe",
      "Talon",
      "Plateau",
      "Cave"
    ],
    "map": [
      50,
      66
    ],
    "regionId": "auvergne-rhone-alpes"
  },
  {
    "id": "salers",
    "nom": "Salers",
    "alt": [
      "Salers tradition"
    ],
    "dept": "Cantal (15)",
    "commune": "Monts du Cantal",
    "lait": "Vache",
    "race": "Salers",
    "famille": "Pâte pressée non cuite",
    "croute": "Épaisse, dorée à brune",
    "texture": "Ferme, fondante",
    "forme": "Fourme haute",
    "poids": "35–50 kg",
    "dim": "Ø 40 cm",
    "affinage": "3 mois minimum",
    "mg": "45 %",
    "saison": "Été (avr.–nov., pleine herbe)",
    "intensite": 4,
    "aop": true,
    "prix": "≈ 26 €/kg",
    "dispo": "Saisonnière",
    "color": "Jaune ambré",
    "notes": [
      "Puissant",
      "Herbe fraîche",
      "Épices",
      "Fruité"
    ],
    "accords": {
      "vin": "Marcillac, Cahors",
      "biere": "Ambrée",
      "cidre": "Cidre brut",
      "whisky": "Highlands",
      "pain": "Pain de seigle"
    },
    "histoire": "Fromage fermier de tradition, fabriqué uniquement à la période de pâturage dans la « gerle » de bois, avec le lait de vaches Salers.",
    "nutrition": {
      "energie": "395 kcal",
      "proteines": "23 g",
      "lipides": "33 g",
      "calcium": "720 mg"
    },
    "galerie": [
      "Fourme",
      "Coupe",
      "Talon",
      "Plateau",
      "Buron"
    ],
    "map": [
      52,
      61
    ],
    "regionId": "auvergne-rhone-alpes"
  },
  {
    "id": "raclette-savoie",
    "nom": "Raclette de Savoie",
    "alt": [],
    "dept": "Savoie / Haute-Savoie (73/74)",
    "commune": "Alpes du Nord",
    "lait": "Vache",
    "race": "Abondance, Tarine, Montbéliarde",
    "famille": "Pâte pressée non cuite",
    "croute": "Frottée, dorée",
    "texture": "Fondante à chaud",
    "forme": "Meule ronde",
    "poids": "5–7 kg",
    "dim": "Ø 30 cm",
    "affinage": "8 semaines minimum",
    "mg": "48 %",
    "saison": "Automne → Hiver",
    "intensite": 2,
    "aop": false,
    "prix": "≈ 20 €/kg",
    "dispo": "Courante",
    "color": "Ivoire",
    "notes": [
      "Doux",
      "Beurre fondu",
      "Lait",
      "Noisette"
    ],
    "accords": {
      "vin": "Vin de Savoie (Apremont)",
      "biere": "Blonde",
      "cidre": "Cidre brut",
      "whisky": "Speyside",
      "pain": "Pain de campagne, pommes de terre"
    },
    "histoire": "Fromage à fondre par excellence des Alpes, IGP : on racle la tranche fondue sur les pommes de terre chaudes.",
    "nutrition": {
      "energie": "360 kcal",
      "proteines": "22 g",
      "lipides": "29 g",
      "calcium": "650 mg"
    },
    "galerie": [
      "Meule",
      "Tranche fondue",
      "Coupe",
      "Plateau",
      "Cave"
    ],
    "map": [
      82,
      68
    ],
    "regionId": "auvergne-rhone-alpes"
  },
  {
    "id": "saint-marcellin",
    "nom": "Saint-Marcellin",
    "alt": [],
    "dept": "Isère (38)",
    "commune": "Sud-Grésivaudan",
    "lait": "Vache",
    "race": "Montbéliarde",
    "famille": "Pâte molle à croûte fleurie",
    "croute": "Fine, fleurie beige",
    "texture": "Crémeuse à coulante",
    "forme": "Petit palet bombé",
    "poids": "80 g",
    "dim": "Ø 7 cm",
    "affinage": "2–6 semaines",
    "mg": "50 %",
    "saison": "Toute l'année",
    "intensite": 2,
    "aop": false,
    "prix": "≈ 30 €/kg",
    "dispo": "Courante",
    "color": "Ivoire",
    "notes": [
      "Lactique",
      "Crème",
      "Champignon",
      "Noisette"
    ],
    "accords": {
      "vin": "Vin du Bugey, Côtes du Rhône",
      "biere": "Blanche",
      "cidre": "Cidre brut",
      "whisky": "Lowlands",
      "pain": "Pain de campagne"
    },
    "histoire": "Jadis fromage de chèvre, devenu fromage de vache. Louis XI, perdu en forêt de Lente, en aurait fait l'éloge.",
    "nutrition": {
      "energie": "300 kcal",
      "proteines": "18 g",
      "lipides": "25 g",
      "calcium": "300 mg"
    },
    "galerie": [
      "Palet",
      "Cœur coulant",
      "Croûte",
      "Plateau",
      "Cave"
    ],
    "map": [
      70,
      64
    ],
    "regionId": "auvergne-rhone-alpes"
  },
  {
    "id": "saint-felicien",
    "nom": "Saint-Félicien",
    "alt": [],
    "dept": "Drôme / Isère (26/38)",
    "commune": "Vallée du Rhône",
    "lait": "Vache",
    "race": "Montbéliarde",
    "famille": "Pâte molle à croûte fleurie",
    "croute": "Fine, fleurie",
    "texture": "Très crémeuse, coulante",
    "forme": "Palet large en faisselle",
    "poids": "180 g",
    "dim": "Ø 10 cm",
    "affinage": "2–4 semaines",
    "mg": "60 %",
    "saison": "Toute l'année",
    "intensite": 2,
    "aop": false,
    "prix": "≈ 28 €/kg",
    "dispo": "Courante",
    "color": "Ivoire",
    "notes": [
      "Crème",
      "Beurre",
      "Champignon",
      "Doux"
    ],
    "accords": {
      "vin": "Saint-Joseph blanc",
      "biere": "Blanche",
      "cidre": "Cidre doux",
      "whisky": "Lowlands",
      "pain": "Baguette"
    },
    "histoire": "Grand cousin plus crémeux du Saint-Marcellin, enrichi de crème et vendu dans sa faisselle.",
    "nutrition": {
      "energie": "340 kcal",
      "proteines": "14 g",
      "lipides": "31 g",
      "calcium": "300 mg"
    },
    "galerie": [
      "En faisselle",
      "Cœur coulant",
      "Croûte",
      "Plateau",
      "Cave"
    ],
    "map": [
      68,
      66
    ],
    "regionId": "auvergne-rhone-alpes"
  },
  {
    "id": "tomme-savoie",
    "nom": "Tomme de Savoie",
    "alt": [],
    "dept": "Savoie / Haute-Savoie (73/74)",
    "commune": "Alpes du Nord",
    "lait": "Vache",
    "race": "Tarine, Abondance, Montbéliarde",
    "famille": "Pâte pressée non cuite",
    "croute": "Naturelle grise, épaisse fleurie",
    "texture": "Souple, moelleuse",
    "forme": "Disque épais",
    "poids": "1,5–2 kg",
    "dim": "Ø 18–20 cm",
    "affinage": "5 semaines minimum",
    "mg": "20–40 % (maigre à mi-gras)",
    "saison": "Toute l'année",
    "intensite": 2,
    "aop": false,
    "prix": "≈ 22 €/kg",
    "dispo": "Courante",
    "color": "Ivoire",
    "notes": [
      "Cave",
      "Champignon",
      "Noisette",
      "Terreux"
    ],
    "accords": {
      "vin": "Vin de Savoie rouge (Mondeuse)",
      "biere": "Ambrée",
      "cidre": "Cidre brut",
      "whisky": "Highlands",
      "pain": "Pain de seigle"
    },
    "histoire": "Fromage « maigre » historique fait avec le lait écrémé restant après le beurre, à la croûte grise couverte de fleurs.",
    "nutrition": {
      "energie": "300 kcal",
      "proteines": "22 g",
      "lipides": "22 g",
      "calcium": "600 mg"
    },
    "galerie": [
      "Disque",
      "Coupe",
      "Croûte grise",
      "Plateau",
      "Cave"
    ],
    "map": [
      82,
      66
    ],
    "regionId": "auvergne-rhone-alpes"
  },
  {
    "id": "tomme-abondance",
    "nom": "Tomme d'Abondance",
    "alt": [],
    "dept": "Haute-Savoie (74)",
    "commune": "Vallée d'Abondance",
    "lait": "Vache",
    "race": "Abondance",
    "famille": "Pâte pressée",
    "croute": "Frottée ambrée",
    "texture": "Ferme, fruitée",
    "forme": "Petite meule",
    "poids": "3–5 kg",
    "dim": "Ø 25 cm",
    "affinage": "2–3 mois",
    "mg": "45 %",
    "saison": "Toute l'année",
    "intensite": 3,
    "aop": false,
    "prix": "≈ 26 €/kg",
    "dispo": "Régionale",
    "color": "Ivoire",
    "notes": [
      "Fruité",
      "Noisette",
      "Beurre"
    ],
    "accords": {
      "vin": "Chignin-Bergeron",
      "biere": "Ambrée",
      "cidre": "Cidre demi-sec",
      "whisky": "Highlands",
      "pain": "Pain de campagne"
    },
    "histoire": "Petite sœur de l'Abondance AOP, fabriquée dans la même vallée avec le lait de la race Abondance.",
    "nutrition": {
      "energie": "380 kcal",
      "proteines": "24 g",
      "lipides": "31 g",
      "calcium": "800 mg"
    },
    "galerie": [
      "Meule",
      "Coupe",
      "Talon",
      "Plateau",
      "Cave"
    ],
    "map": [
      84,
      63
    ],
    "regionId": "auvergne-rhone-alpes"
  },
  {
    "id": "tomme-tarentaise",
    "nom": "Tomme de Tarentaise",
    "alt": [],
    "dept": "Savoie (73)",
    "commune": "Vallée de la Tarentaise",
    "lait": "Vache",
    "race": "Tarine",
    "famille": "Pâte pressée",
    "croute": "Frottée",
    "texture": "Ferme",
    "forme": "Petite meule",
    "poids": "3–4 kg",
    "dim": "Ø 24 cm",
    "affinage": "2 mois+",
    "mg": "45 %",
    "saison": "Été",
    "intensite": 3,
    "aop": false,
    "prix": "≈ 27 €/kg",
    "dispo": "Saisonnière",
    "color": "Ivoire doré",
    "notes": [
      "Alpage",
      "Fruité",
      "Herbe"
    ],
    "accords": {
      "vin": "Roussette de Savoie",
      "biere": "Ambrée",
      "cidre": "Cidre brut",
      "whisky": "Speyside",
      "pain": "Pain de seigle"
    },
    "histoire": "Tomme d'alpage de la haute Tarentaise, au lait de vaches Tarine broutant les pâturages d'altitude.",
    "nutrition": {
      "energie": "380 kcal",
      "proteines": "24 g",
      "lipides": "31 g",
      "calcium": "780 mg"
    },
    "galerie": [
      "Meule",
      "Coupe",
      "Talon",
      "Plateau",
      "Alpage"
    ],
    "map": [
      85,
      69
    ],
    "regionId": "auvergne-rhone-alpes"
  },
  {
    "id": "tomme-bauges",
    "nom": "Tomme fermière des Bauges",
    "alt": [],
    "dept": "Savoie (73)",
    "commune": "Massif des Bauges",
    "lait": "Vache",
    "race": "Tarine, Abondance",
    "famille": "Pâte pressée non cuite",
    "croute": "Naturelle grise",
    "texture": "Souple",
    "forme": "Disque",
    "poids": "1,3 kg",
    "dim": "Ø 18 cm",
    "affinage": "5 semaines",
    "mg": "40 %",
    "saison": "Toute l'année",
    "intensite": 2,
    "aop": false,
    "prix": "≈ 23 €/kg",
    "dispo": "Régionale",
    "color": "Ivoire",
    "notes": [
      "Cave",
      "Noisette",
      "Doux"
    ],
    "accords": {
      "vin": "Vin de Savoie",
      "biere": "Blonde",
      "cidre": "Cidre brut",
      "whisky": "Highlands",
      "pain": "Pain de campagne"
    },
    "histoire": "Tomme du parc naturel des Bauges, produite en fruitières et à la ferme.",
    "nutrition": {
      "energie": "310 kcal",
      "proteines": "22 g",
      "lipides": "23 g",
      "calcium": "600 mg"
    },
    "galerie": [
      "Disque",
      "Coupe",
      "Croûte",
      "Plateau",
      "Cave"
    ],
    "map": [
      81,
      66
    ],
    "regionId": "auvergne-rhone-alpes"
  },
  {
    "id": "tomme-belledonne",
    "nom": "Tomme de Belledonne",
    "alt": [],
    "dept": "Isère (38)",
    "commune": "Massif de Belledonne",
    "lait": "Vache",
    "race": "Montbéliarde",
    "famille": "Pâte pressée",
    "croute": "Naturelle grise",
    "texture": "Souple",
    "forme": "Disque",
    "poids": "1,5 kg",
    "dim": "Ø 18 cm",
    "affinage": "6 semaines",
    "mg": "40 %",
    "saison": "Toute l'année",
    "intensite": 2,
    "aop": false,
    "prix": "≈ 23 €/kg",
    "dispo": "Régionale",
    "color": "Ivoire",
    "notes": [
      "Cave",
      "Noisette",
      "Terreux"
    ],
    "accords": {
      "vin": "Vin du Grésivaudan",
      "biere": "Ambrée",
      "cidre": "Cidre brut",
      "whisky": "Highlands",
      "pain": "Pain de seigle"
    },
    "histoire": "Tomme de montagne du massif de Belledonne, dans la tradition des tommes grises alpines.",
    "nutrition": {
      "energie": "310 kcal",
      "proteines": "22 g",
      "lipides": "23 g",
      "calcium": "600 mg"
    },
    "galerie": [
      "Disque",
      "Coupe",
      "Croûte",
      "Plateau",
      "Cave"
    ],
    "map": [
      76,
      66
    ],
    "regionId": "auvergne-rhone-alpes"
  },
  {
    "id": "tomme-chevre-vercors",
    "nom": "Tomme de Chèvre du Vercors",
    "alt": [],
    "dept": "Isère / Drôme (38/26)",
    "commune": "Massif du Vercors",
    "lait": "Chèvre",
    "race": "Alpine",
    "famille": "Pâte pressée non cuite",
    "croute": "Naturelle fleurie",
    "texture": "Ferme, fondante",
    "forme": "Petite meule",
    "poids": "0,8–1,2 kg",
    "dim": "Ø 15 cm",
    "affinage": "1–2 mois",
    "mg": "45 %",
    "saison": "Printemps → Automne",
    "intensite": 3,
    "aop": false,
    "prix": "≈ 32 €/kg",
    "dispo": "Saisonnière",
    "color": "Blanc à ivoire",
    "notes": [
      "Caprin",
      "Noisette",
      "Fleurs",
      "Cave"
    ],
    "accords": {
      "vin": "Clairette de Die",
      "biere": "Blanche",
      "cidre": "Cidre sec",
      "whisky": "Lowlands",
      "pain": "Pain aux céréales"
    },
    "histoire": "Tomme caprine des fermes du Vercors, à la croûte grise fleurie et au goût de chèvre franc.",
    "nutrition": {
      "energie": "340 kcal",
      "proteines": "23 g",
      "lipides": "27 g",
      "calcium": "500 mg"
    },
    "galerie": [
      "Meule",
      "Coupe",
      "Croûte",
      "Plateau",
      "Cave"
    ],
    "map": [
      72,
      67
    ],
    "regionId": "auvergne-rhone-alpes"
  },
  {
    "id": "tomme-champsaur",
    "nom": "Tomme du Champsaur",
    "alt": [],
    "dept": "Hautes-Alpes (05)",
    "commune": "Vallée du Champsaur",
    "lait": "Mélange (vache et chèvre)",
    "race": "Locales alpines",
    "famille": "Pâte pressée",
    "croute": "Naturelle",
    "texture": "Souple",
    "forme": "Disque",
    "poids": "1 kg",
    "dim": "Ø 16 cm",
    "affinage": "1 mois+",
    "mg": "40 %",
    "saison": "Été",
    "intensite": 2,
    "aop": false,
    "prix": "≈ 25 €/kg",
    "dispo": "Régionale",
    "color": "Ivoire",
    "notes": [
      "Doux",
      "Herbe",
      "Noisette"
    ],
    "accords": {
      "vin": "Vin des Hautes-Alpes",
      "biere": "Blonde",
      "cidre": "Cidre brut",
      "whisky": "Highlands",
      "pain": "Pain de campagne"
    },
    "histoire": "Tomme paysanne de la vallée alpine du Champsaur, parfois issue d'un mélange de laits selon les fermes.",
    "nutrition": {
      "energie": "320 kcal",
      "proteines": "22 g",
      "lipides": "24 g",
      "calcium": "600 mg"
    },
    "galerie": [
      "Disque",
      "Coupe",
      "Croûte",
      "Plateau",
      "Alpage"
    ],
    "map": [
      83,
      74
    ],
    "regionId": "auvergne-rhone-alpes"
  },
  {
    "id": "tomme-trieves",
    "nom": "Tomme du Trièves",
    "alt": [],
    "dept": "Isère (38)",
    "commune": "Plateau du Trièves",
    "lait": "Vache",
    "race": "Montbéliarde",
    "famille": "Pâte pressée",
    "croute": "Naturelle grise",
    "texture": "Souple",
    "forme": "Disque",
    "poids": "1,4 kg",
    "dim": "Ø 18 cm",
    "affinage": "6 semaines",
    "mg": "40 %",
    "saison": "Toute l'année",
    "intensite": 2,
    "aop": false,
    "prix": "≈ 23 €/kg",
    "dispo": "Régionale",
    "color": "Ivoire",
    "notes": [
      "Cave",
      "Noisette",
      "Doux"
    ],
    "accords": {
      "vin": "Vin de Savoie",
      "biere": "Blonde",
      "cidre": "Cidre brut",
      "whisky": "Highlands",
      "pain": "Pain de seigle"
    },
    "histoire": "Tomme du plateau du Trièves, au sud du Vercors, produite en ferme.",
    "nutrition": {
      "energie": "310 kcal",
      "proteines": "22 g",
      "lipides": "23 g",
      "calcium": "600 mg"
    },
    "galerie": [
      "Disque",
      "Coupe",
      "Croûte",
      "Plateau",
      "Cave"
    ],
    "map": [
      73,
      69
    ],
    "regionId": "auvergne-rhone-alpes"
  },
  {
    "id": "tomme-champsaur2",
    "nom": "Tommette de Brebis du Velay",
    "alt": [],
    "dept": "Haute-Loire (43)",
    "commune": "Velay",
    "lait": "Brebis",
    "race": "Lacaune",
    "famille": "Pâte pressée non cuite",
    "croute": "Naturelle",
    "texture": "Ferme, fondante",
    "forme": "Petite tommette",
    "poids": "0,5–0,8 kg",
    "dim": "Ø 12 cm",
    "affinage": "1–2 mois",
    "mg": "50 %",
    "saison": "Printemps → Été",
    "intensite": 3,
    "aop": false,
    "prix": "≈ 34 €/kg",
    "dispo": "Régionale",
    "color": "Ivoire",
    "notes": [
      "Lanoline",
      "Noisette",
      "Doux",
      "Brebis"
    ],
    "accords": {
      "vin": "Saint-Pourçain",
      "biere": "Ambrée",
      "cidre": "Cidre brut",
      "whisky": "Speyside",
      "pain": "Pain aux noix"
    },
    "histoire": "Petite tomme au lait de brebis Lacaune du plateau du Velay volcanique.",
    "nutrition": {
      "energie": "360 kcal",
      "proteines": "24 g",
      "lipides": "29 g",
      "calcium": "700 mg"
    },
    "galerie": [
      "Tommette",
      "Coupe",
      "Croûte",
      "Plateau",
      "Cave"
    ],
    "map": [
      58,
      63
    ],
    "regionId": "auvergne-rhone-alpes"
  },
  {
    "id": "tommette-chevre-lyonnais",
    "nom": "Tommette de Chèvre des Monts du Lyonnais",
    "alt": [],
    "dept": "Rhône (69)",
    "commune": "Monts du Lyonnais",
    "lait": "Chèvre",
    "race": "Alpine",
    "famille": "Pâte pressée non cuite",
    "croute": "Naturelle fleurie",
    "texture": "Ferme",
    "forme": "Petite tommette",
    "poids": "0,4–0,6 kg",
    "dim": "Ø 11 cm",
    "affinage": "1 mois",
    "mg": "45 %",
    "saison": "Printemps → Automne",
    "intensite": 3,
    "aop": false,
    "prix": "≈ 34 €/kg",
    "dispo": "Régionale",
    "color": "Blanc à ivoire",
    "notes": [
      "Caprin",
      "Noisette",
      "Fleurs"
    ],
    "accords": {
      "vin": "Coteaux du Lyonnais",
      "biere": "Blanche",
      "cidre": "Cidre sec",
      "whisky": "Lowlands",
      "pain": "Pain aux céréales"
    },
    "histoire": "Tommette caprine des Monts du Lyonnais, pays de petites fermes fromagères.",
    "nutrition": {
      "energie": "340 kcal",
      "proteines": "23 g",
      "lipides": "27 g",
      "calcium": "500 mg"
    },
    "galerie": [
      "Tommette",
      "Coupe",
      "Croûte",
      "Plateau",
      "Cave"
    ],
    "map": [
      63,
      60
    ],
    "regionId": "auvergne-rhone-alpes"
  },
  {
    "id": "charolais",
    "nom": "Charolais",
    "alt": [],
    "dept": "Saône-et-Loire limitrophe / Rhône (69)",
    "commune": "Brionnais-Charolais",
    "lait": "Chèvre",
    "race": "Alpine",
    "famille": "Pâte molle à croûte naturelle",
    "croute": "Naturelle, bleutée",
    "texture": "Ferme, fine",
    "forme": "Tonnelet vertical",
    "poids": "250–310 g",
    "dim": "Ø 6–7 cm · h 8 cm",
    "affinage": "2–4 semaines",
    "mg": "45 %",
    "saison": "Printemps → Automne",
    "intensite": 3,
    "aop": true,
    "prix": "≈ 42 €/kg",
    "dispo": "Saisonnière",
    "color": "Blanc ivoire",
    "notes": [
      "Caprin",
      "Noisette",
      "Cave",
      "Fleurs"
    ],
    "accords": {
      "vin": "Mâcon-Villages, Pouilly-Fuissé",
      "biere": "Blanche",
      "cidre": "Cidre sec",
      "whisky": "Lowlands",
      "pain": "Pain aux céréales"
    },
    "histoire": "Fromage de chèvre en tonnelet du pays charolais, historiquement fabriqué par les femmes d'éleveurs de bovins.",
    "nutrition": {
      "energie": "320 kcal",
      "proteines": "20 g",
      "lipides": "26 g",
      "calcium": "160 mg"
    },
    "galerie": [
      "Tonnelet",
      "Coupe",
      "Croûte bleutée",
      "Plateau",
      "Cave"
    ],
    "map": [
      64,
      55
    ],
    "regionId": "auvergne-rhone-alpes"
  },
  {
    "id": "persille-aravis",
    "nom": "Persillé des Aravis",
    "alt": [
      "Persillé de Thônes"
    ],
    "dept": "Haute-Savoie (74)",
    "commune": "Massif des Aravis",
    "lait": "Chèvre (parfois mélange)",
    "race": "Alpine",
    "famille": "Pâte persillée",
    "croute": "Naturelle, sèche",
    "texture": "Ferme, friable, persillée",
    "forme": "Petit cylindre",
    "poids": "0,8–1 kg",
    "dim": "Ø 12 cm",
    "affinage": "1–3 mois",
    "mg": "45 %",
    "saison": "Été → Automne",
    "intensite": 4,
    "aop": false,
    "prix": "≈ 48 €/kg",
    "dispo": "Rare",
    "color": "Blanc veiné de bleu",
    "notes": [
      "Caprin puissant",
      "Épices",
      "Cave",
      "Piquant"
    ],
    "accords": {
      "vin": "Vin de Savoie moelleux",
      "biere": "Ambrée",
      "cidre": "Cidre doux",
      "whisky": "Islay",
      "pain": "Pain aux fruits secs"
    },
    "histoire": "Rarissime bleu de chèvre des Aravis, l'un des seuls persillés caprins de France, fabriqué par quelques fermes.",
    "nutrition": {
      "energie": "350 kcal",
      "proteines": "22 g",
      "lipides": "28 g",
      "calcium": "300 mg"
    },
    "galerie": [
      "Cylindre",
      "Coupe persillée",
      "Intérieur",
      "Plateau",
      "Cave"
    ],
    "map": [
      83,
      67
    ],
    "regionId": "auvergne-rhone-alpes"
  },
  {
    "id": "gaperon",
    "nom": "Gaperon",
    "alt": [
      "Gapron"
    ],
    "dept": "Puy-de-Dôme (63)",
    "commune": "Limagne",
    "lait": "Vache (babeurre)",
    "race": "Locales",
    "famille": "Pâte pressée aromatisée",
    "croute": "Naturelle sèche",
    "texture": "Ferme",
    "forme": "Demi-boule ficelée",
    "poids": "300–450 g",
    "dim": "Ø 9 cm",
    "affinage": "1–2 mois",
    "mg": "30 %",
    "saison": "Toute l'année",
    "intensite": 4,
    "aop": false,
    "prix": "≈ 30 €/kg",
    "dispo": "Régionale",
    "color": "Ivoire piqueté",
    "notes": [
      "Ail",
      "Poivre",
      "Piquant",
      "Rustique"
    ],
    "accords": {
      "vin": "Côtes d'Auvergne rouge",
      "biere": "Brune",
      "cidre": "Cidre brut",
      "whisky": "Highlands",
      "pain": "Pain de seigle"
    },
    "histoire": "Fromage de babeurre (« gape » en patois) parfumé d'ail et de poivre, jadis suspendu à la cheminée. On disait la richesse d'une ferme au nombre de gaperons pendus.",
    "nutrition": {
      "energie": "280 kcal",
      "proteines": "22 g",
      "lipides": "20 g",
      "calcium": "400 mg"
    },
    "galerie": [
      "Demi-boule",
      "Coupe",
      "Croûte ficelée",
      "Plateau",
      "Cheminée"
    ],
    "map": [
      56,
      59
    ],
    "regionId": "auvergne-rhone-alpes"
  },
  {
    "id": "carre-aurillac",
    "nom": "Carré d'Aurillac",
    "alt": [],
    "dept": "Cantal (15)",
    "commune": "Bassin d'Aurillac",
    "lait": "Vache",
    "race": "Salers, Montbéliarde",
    "famille": "Pâte persillée",
    "croute": "Naturelle",
    "texture": "Onctueuse, persillée",
    "forme": "Pavé carré",
    "poids": "1,2–1,5 kg",
    "dim": "10 × 10 cm",
    "affinage": "1–2 mois",
    "mg": "50 %",
    "saison": "Toute l'année",
    "intensite": 4,
    "aop": false,
    "prix": "≈ 22 €/kg",
    "dispo": "Régionale",
    "color": "Ivoire veiné",
    "notes": [
      "Puissant",
      "Beurre",
      "Champignon",
      "Épices"
    ],
    "accords": {
      "vin": "Banyuls",
      "biere": "Stout",
      "cidre": "Cidre doux",
      "whisky": "Islay",
      "pain": "Pain aux fruits secs"
    },
    "histoire": "Bleu carré d'Auvergne, proche du Bleu d'Auvergne mais moulé en pavé, spécialité du bassin d'Aurillac.",
    "nutrition": {
      "energie": "355 kcal",
      "proteines": "19 g",
      "lipides": "30 g",
      "calcium": "550 mg"
    },
    "galerie": [
      "Pavé",
      "Coupe",
      "Intérieur",
      "Plateau",
      "Cave"
    ],
    "map": [
      52,
      63
    ],
    "regionId": "auvergne-rhone-alpes"
  },
  {
    "id": "pave-affinois",
    "nom": "Pavé d'Affinois",
    "alt": [],
    "dept": "Isère (38)",
    "commune": "Pélussin / région lyonnaise",
    "lait": "Vache",
    "race": "Montbéliarde",
    "famille": "Pâte molle à croûte fleurie",
    "croute": "Fine, fleurie blanche",
    "texture": "Ultra-crémeuse, coulante",
    "forme": "Pavé carré",
    "poids": "150 g",
    "dim": "8 × 8 cm",
    "affinage": "2 semaines",
    "mg": "60 %",
    "saison": "Toute l'année",
    "intensite": 1,
    "aop": false,
    "prix": "≈ 24 €/kg",
    "dispo": "Courante",
    "color": "Blanc ivoire",
    "notes": [
      "Crème",
      "Beurre",
      "Doux",
      "Champignon"
    ],
    "accords": {
      "vin": "Crémant, Chardonnay",
      "biere": "Blanche",
      "cidre": "Cidre doux",
      "whisky": "Lowlands",
      "pain": "Baguette"
    },
    "histoire": "Fromage moderne à pâte ultra-fondante obtenu par ultrafiltration du lait, très populaire pour sa douceur crémeuse.",
    "nutrition": {
      "energie": "360 kcal",
      "proteines": "13 g",
      "lipides": "33 g",
      "calcium": "300 mg"
    },
    "galerie": [
      "Pavé",
      "Coupe",
      "Croûte",
      "Plateau",
      "Cave"
    ],
    "map": [
      66,
      61
    ],
    "regionId": "auvergne-rhone-alpes"
  },
  {
    "id": "fourme-montbrison",
    "nom": "Fourme de Montbrison",
    "alt": [],
    "dept": "Loire / Puy-de-Dôme (42/63)",
    "commune": "Monts du Forez",
    "lait": "Vache",
    "race": "Montbéliarde",
    "famille": "Pâte persillée",
    "croute": "Naturelle orangée, sèche",
    "texture": "Ferme, fondante, persillée",
    "forme": "Haut cylindre",
    "poids": "2–2,5 kg",
    "dim": "Ø 13 cm · h 19 cm",
    "affinage": "1 mois minimum",
    "mg": "50 %",
    "saison": "Toute l'année",
    "intensite": 3,
    "aop": true,
    "prix": "≈ 24 €/kg",
    "dispo": "Courante",
    "color": "Ivoire à jaune, veiné",
    "notes": [
      "Doux",
      "Fruité",
      "Beurre",
      "Cave"
    ],
    "accords": {
      "vin": "Côtes du Forez, moelleux",
      "biere": "Blonde d'abbaye",
      "cidre": "Cidre doux",
      "whisky": "Speyside",
      "pain": "Pain aux noix"
    },
    "histoire": "Longtemps confondue avec la Fourme d'Ambert, elle s'en distingue par sa croûte orangée et son ressuyage sur des gouttières d'épicéa.",
    "nutrition": {
      "energie": "348 kcal",
      "proteines": "20 g",
      "lipides": "29 g",
      "calcium": "540 mg"
    },
    "galerie": [
      "Cylindre",
      "Coupe",
      "Croûte orangée",
      "Plateau",
      "Cave"
    ],
    "map": [
      59,
      59
    ],
    "regionId": "auvergne-rhone-alpes"
  },
  {
    "id": "comtomme",
    "nom": "Comtomme",
    "alt": [],
    "dept": "Ain (01)",
    "commune": "Bugey",
    "lait": "Vache",
    "race": "Montbéliarde",
    "famille": "Pâte pressée",
    "croute": "Frottée",
    "texture": "Souple, fondante",
    "forme": "Meule",
    "poids": "4–5 kg",
    "dim": "Ø 28 cm",
    "affinage": "2–3 mois",
    "mg": "45 %",
    "saison": "Toute l'année",
    "intensite": 2,
    "aop": false,
    "prix": "≈ 24 €/kg",
    "dispo": "Régionale",
    "color": "Ivoire",
    "notes": [
      "Doux",
      "Fruité",
      "Beurre",
      "Noisette"
    ],
    "accords": {
      "vin": "Vin du Bugey",
      "biere": "Ambrée",
      "cidre": "Cidre demi-sec",
      "whisky": "Highlands",
      "pain": "Pain de campagne"
    },
    "histoire": "Tomme pressée du Bugey inspirée des grandes pâtes cuites jurassiennes, douce et fondante.",
    "nutrition": {
      "energie": "360 kcal",
      "proteines": "24 g",
      "lipides": "28 g",
      "calcium": "750 mg"
    },
    "galerie": [
      "Meule",
      "Coupe",
      "Talon",
      "Plateau",
      "Cave"
    ],
    "map": [
      74,
      56
    ],
    "regionId": "auvergne-rhone-alpes"
  },
  {
    "id": "serac",
    "nom": "Sérac",
    "alt": [
      "Séré"
    ],
    "dept": "Savoie / Haute-Savoie (73/74)",
    "commune": "Alpes du Nord",
    "lait": "Vache (petit-lait)",
    "race": "Tarine, Abondance",
    "famille": "Pâte fraîche (lactosérum)",
    "croute": "Aucune",
    "texture": "Granuleuse, ferme",
    "forme": "Motte ou cône",
    "poids": "200–400 g",
    "dim": "variable",
    "affinage": "Frais à 2 semaines (parfois fumé)",
    "mg": "5–15 %",
    "saison": "Été",
    "intensite": 1,
    "aop": false,
    "prix": "≈ 14 €/kg",
    "dispo": "Régionale",
    "color": "Blanc",
    "notes": [
      "Lacté",
      "Frais",
      "Doux",
      "Fumé (variante)"
    ],
    "accords": {
      "vin": "Vin de Savoie blanc",
      "biere": "Blanche",
      "cidre": "Cidre doux",
      "whisky": "Lowlands",
      "pain": "Pain de campagne"
    },
    "histoire": "Fromage de récupération fait avec le petit-lait chauffé restant de la fabrication du Beaufort ou de l'Abondance : rien ne se perd en alpage.",
    "nutrition": {
      "energie": "120 kcal",
      "proteines": "14 g",
      "lipides": "5 g",
      "calcium": "200 mg"
    },
    "galerie": [
      "Motte",
      "Coupe",
      "Texture",
      "Plateau",
      "Chalet"
    ],
    "map": [
      83,
      67
    ],
    "regionId": "auvergne-rhone-alpes"
  },
  {
    "id": "vacherin-abondance",
    "nom": "Vacherin d'Abondance",
    "alt": [],
    "dept": "Haute-Savoie (74)",
    "commune": "Vallée d'Abondance",
    "lait": "Vache",
    "race": "Abondance",
    "famille": "Pâte molle à croûte lavée",
    "croute": "Lavée, sanglée d'épicéa",
    "texture": "Coulante",
    "forme": "Disque en sangle d'épicéa",
    "poids": "0,5–1 kg",
    "dim": "Ø 12–15 cm",
    "affinage": "3 semaines+",
    "mg": "45 %",
    "saison": "Automne → Hiver",
    "intensite": 3,
    "aop": false,
    "prix": "≈ 32 €/kg",
    "dispo": "Saisonnière",
    "color": "Ivoire crémeux",
    "notes": [
      "Résine",
      "Crème",
      "Sous-bois"
    ],
    "accords": {
      "vin": "Vin de Savoie, vin jaune",
      "biere": "Blonde d'hiver",
      "cidre": "Cidre demi-sec",
      "whisky": "Highlands boisé",
      "pain": "Pain de campagne"
    },
    "histoire": "Vacherin fermier de la vallée d'Abondance, sanglé d'épicéa, cousin savoyard du Mont d'Or.",
    "nutrition": {
      "energie": "300 kcal",
      "proteines": "16 g",
      "lipides": "26 g",
      "calcium": "450 mg"
    },
    "galerie": [
      "Sanglé",
      "Cœur coulant",
      "Croûte",
      "Boîte chaude",
      "Cave"
    ],
    "map": [
      84,
      64
    ],
    "regionId": "auvergne-rhone-alpes"
  },
  {
    "id": "vacherin-bauges",
    "nom": "Vacherin des Bauges",
    "alt": [],
    "dept": "Savoie (73)",
    "commune": "Massif des Bauges",
    "lait": "Vache",
    "race": "Tarine, Abondance",
    "famille": "Pâte molle à croûte lavée",
    "croute": "Lavée, sanglée d'épicéa",
    "texture": "Coulante",
    "forme": "Disque sanglé",
    "poids": "0,5–1 kg",
    "dim": "Ø 13 cm",
    "affinage": "3 semaines+",
    "mg": "45 %",
    "saison": "Automne → Hiver",
    "intensite": 3,
    "aop": false,
    "prix": "≈ 32 €/kg",
    "dispo": "Saisonnière",
    "color": "Ivoire crémeux",
    "notes": [
      "Résine",
      "Crème",
      "Sous-bois"
    ],
    "accords": {
      "vin": "Vin de Savoie",
      "biere": "Blonde d'hiver",
      "cidre": "Cidre demi-sec",
      "whisky": "Highlands boisé",
      "pain": "Pain de campagne"
    },
    "histoire": "Vacherin fermier des Bauges sanglé d'écorce d'épicéa, à déguster à la cuillère ou chaud.",
    "nutrition": {
      "energie": "300 kcal",
      "proteines": "16 g",
      "lipides": "26 g",
      "calcium": "450 mg"
    },
    "galerie": [
      "Sanglé",
      "Cœur coulant",
      "Croûte",
      "Boîte chaude",
      "Cave"
    ],
    "map": [
      81,
      65
    ],
    "regionId": "auvergne-rhone-alpes"
  },
  {
    "id": "bleu-thiezac",
    "nom": "Bleu de Thiézac",
    "alt": [],
    "dept": "Cantal (15)",
    "commune": "Vallée de la Cère",
    "lait": "Vache",
    "race": "Salers",
    "famille": "Pâte persillée",
    "croute": "Naturelle",
    "texture": "Onctueuse",
    "forme": "Cylindre",
    "poids": "2–3 kg",
    "dim": "Ø 20 cm",
    "affinage": "1–2 mois",
    "mg": "50 %",
    "saison": "Été → Automne",
    "intensite": 4,
    "aop": false,
    "prix": "≈ 24 €/kg",
    "dispo": "Rare",
    "color": "Ivoire veiné",
    "notes": [
      "Puissant",
      "Champignon",
      "Épices"
    ],
    "accords": {
      "vin": "Banyuls",
      "biere": "Stout",
      "cidre": "Cidre doux",
      "whisky": "Islay",
      "pain": "Pain aux fruits secs"
    },
    "histoire": "Bleu fermier de la vallée de la Cère près de Thiézac, dans la tradition des bleus d'Auvergne.",
    "nutrition": {
      "energie": "354 kcal",
      "proteines": "19 g",
      "lipides": "30 g",
      "calcium": "550 mg"
    },
    "galerie": [
      "Cylindre",
      "Coupe",
      "Intérieur",
      "Plateau",
      "Cave"
    ],
    "map": [
      52,
      62
    ],
    "regionId": "auvergne-rhone-alpes"
  },
  {
    "id": "bleu-laqueuille",
    "nom": "Bleu de Laqueuille",
    "alt": [],
    "dept": "Puy-de-Dôme (63)",
    "commune": "Laqueuille",
    "lait": "Vache",
    "race": "Montbéliarde",
    "famille": "Pâte persillée",
    "croute": "Naturelle",
    "texture": "Onctueuse",
    "forme": "Cylindre",
    "poids": "2–2,5 kg",
    "dim": "Ø 20 cm",
    "affinage": "1 mois+",
    "mg": "50 %",
    "saison": "Toute l'année",
    "intensite": 3,
    "aop": false,
    "prix": "≈ 23 €/kg",
    "dispo": "Régionale",
    "color": "Ivoire veiné",
    "notes": [
      "Doux",
      "Champignon",
      "Beurre"
    ],
    "accords": {
      "vin": "Maury",
      "biere": "Brune",
      "cidre": "Cidre doux",
      "whisky": "Speyside",
      "pain": "Pain aux figues"
    },
    "histoire": "Berceau du bleu à la moisissure de pain : c'est à Laqueuille qu'Antoine Roussel inventa la technique d'ensemencement vers 1850.",
    "nutrition": {
      "energie": "350 kcal",
      "proteines": "19 g",
      "lipides": "30 g",
      "calcium": "550 mg"
    },
    "galerie": [
      "Cylindre",
      "Coupe",
      "Intérieur",
      "Plateau",
      "Cave"
    ],
    "map": [
      55,
      60
    ],
    "regionId": "auvergne-rhone-alpes"
  },
  {
    "id": "murol",
    "nom": "Murol",
    "alt": [],
    "dept": "Puy-de-Dôme (63)",
    "commune": "Murol",
    "lait": "Vache",
    "race": "Salers, Montbéliarde",
    "famille": "Pâte pressée non cuite",
    "croute": "Lavée, rouge orangé",
    "texture": "Souple, fondante",
    "forme": "Disque percé au centre",
    "poids": "450 g",
    "dim": "Ø 12 cm",
    "affinage": "5 semaines",
    "mg": "45 %",
    "saison": "Toute l'année",
    "intensite": 2,
    "aop": false,
    "prix": "≈ 22 €/kg",
    "dispo": "Régionale",
    "color": "Ivoire",
    "notes": [
      "Doux",
      "Beurre",
      "Noisette"
    ],
    "accords": {
      "vin": "Côtes d'Auvergne",
      "biere": "Blonde",
      "cidre": "Cidre brut",
      "whisky": "Highlands",
      "pain": "Pain de campagne"
    },
    "histoire": "Créé au début du XXᵉ siècle à partir du Saint-Nectaire, reconnaissable à son trou central : la carotte prélevée était vendue comme « Trou de Murol ».",
    "nutrition": {
      "energie": "330 kcal",
      "proteines": "20 g",
      "lipides": "27 g",
      "calcium": "560 mg"
    },
    "galerie": [
      "Disque percé",
      "Coupe",
      "Croûte",
      "Plateau",
      "Cave"
    ],
    "map": [
      55,
      61
    ],
    "regionId": "auvergne-rhone-alpes"
  },
  {
    "id": "rochebaron",
    "nom": "Rochebaron",
    "alt": [],
    "dept": "Haute-Loire (43)",
    "commune": "Bas-en-Basset",
    "lait": "Vache",
    "race": "Montbéliarde",
    "famille": "Pâte persillée",
    "croute": "Cendrée, duveteuse grise",
    "texture": "Crémeuse, persillée fine",
    "forme": "Cylindre",
    "poids": "0,5–2,5 kg",
    "dim": "Ø 12 cm",
    "affinage": "3–4 semaines",
    "mg": "50 %",
    "saison": "Toute l'année",
    "intensite": 3,
    "aop": false,
    "prix": "≈ 22 €/kg",
    "dispo": "Courante",
    "color": "Ivoire veiné, croûte cendrée",
    "notes": [
      "Doux",
      "Crème",
      "Champignon",
      "Cave"
    ],
    "accords": {
      "vin": "Sauternes",
      "biere": "Blonde d'abbaye",
      "cidre": "Cidre doux",
      "whisky": "Speyside",
      "pain": "Pain aux noix"
    },
    "histoire": "Bleu crémeux du Velay reconnaissable à sa croûte cendrée duveteuse, nommé d'après le château de Rochebaron.",
    "nutrition": {
      "energie": "350 kcal",
      "proteines": "18 g",
      "lipides": "30 g",
      "calcium": "540 mg"
    },
    "galerie": [
      "Cylindre cendré",
      "Coupe",
      "Intérieur",
      "Plateau",
      "Cave"
    ],
    "map": [
      59,
      62
    ],
    "regionId": "auvergne-rhone-alpes"
  },
  {
    "id": "bouton-culotte",
    "nom": "Bouton de Culotte",
    "alt": [
      "Cul de bouc",
      "Chevreton du Mâconnais"
    ],
    "dept": "Rhône / Saône-et-Loire limitrophe (69)",
    "commune": "Haut-Beaujolais / Mâconnais",
    "lait": "Chèvre (parfois mélange)",
    "race": "Alpine",
    "famille": "Pâte molle à croûte naturelle",
    "croute": "Naturelle, bleutée",
    "texture": "Ferme à sèche",
    "forme": "Minuscule tronc-cône",
    "poids": "20–30 g",
    "dim": "Ø 3–4 cm",
    "affinage": "2 semaines → sec",
    "mg": "45 %",
    "saison": "Printemps → Automne",
    "intensite": 3,
    "aop": false,
    "prix": "≈ 45 €/kg",
    "dispo": "Rare",
    "color": "Ivoire",
    "notes": [
      "Caprin",
      "Noisette",
      "Piquant (sec)",
      "Cave"
    ],
    "accords": {
      "vin": "Mâcon-Villages, Beaujolais blanc",
      "biere": "Blanche",
      "cidre": "Cidre sec",
      "whisky": "Lowlands",
      "pain": "Pain aux céréales"
    },
    "histoire": "Le plus petit fromage de France : sa taille de bouton permettait de le saisir d'une main pour recoudre… un bouton de culotte. Séché, il se conserve tout l'hiver.",
    "nutrition": {
      "energie": "320 kcal",
      "proteines": "21 g",
      "lipides": "26 g",
      "calcium": "160 mg"
    },
    "galerie": [
      "Boutons",
      "Coupe",
      "Croûte",
      "Plateau",
      "Séchoir"
    ],
    "map": [
      63,
      56
    ],
    "regionId": "auvergne-rhone-alpes"
  },
  {
    "id": "claousou",
    "nom": "Claousou",
    "alt": [],
    "dept": "Lozère limitrophe / Haute-Loire (43)",
    "commune": "Marges du Massif central",
    "lait": "Brebis",
    "race": "Lacaune",
    "famille": "Pâte pressée non cuite",
    "croute": "Naturelle",
    "texture": "Ferme, fondante",
    "forme": "Petite tomme",
    "poids": "0,5 kg",
    "dim": "Ø 11 cm",
    "affinage": "1–2 mois",
    "mg": "50 %",
    "saison": "Printemps → Été",
    "intensite": 3,
    "aop": false,
    "prix": "≈ 36 €/kg",
    "dispo": "Rare",
    "color": "Ivoire",
    "notes": [
      "Brebis",
      "Noisette",
      "Lanoline",
      "Doux"
    ],
    "accords": {
      "vin": "Vin d'Auvergne blanc",
      "biere": "Ambrée",
      "cidre": "Cidre brut",
      "whisky": "Speyside",
      "pain": "Pain aux noix"
    },
    "histoire": "Petite tomme de brebis des confins du Massif central, production fermière confidentielle.",
    "nutrition": {
      "energie": "360 kcal",
      "proteines": "24 g",
      "lipides": "29 g",
      "calcium": "700 mg"
    },
    "galerie": [
      "Tomme",
      "Coupe",
      "Croûte",
      "Plateau",
      "Cave"
    ],
    "map": [
      56,
      64
    ],
    "regionId": "auvergne-rhone-alpes"
  },
  {
    "id": "galet-loire",
    "nom": "Galet de la Loire",
    "alt": [
      "Galet du Forez"
    ],
    "dept": "Loire (42)",
    "commune": "Plaine du Forez",
    "lait": "Chèvre",
    "race": "Alpine",
    "famille": "Pâte molle à croûte fleurie",
    "croute": "Fine, fleurie blanche",
    "texture": "Crémeuse",
    "forme": "Galet plat",
    "poids": "80–120 g",
    "dim": "Ø 7 cm",
    "affinage": "2–3 semaines",
    "mg": "45 %",
    "saison": "Printemps → Automne",
    "intensite": 2,
    "aop": false,
    "prix": "≈ 36 €/kg",
    "dispo": "Régionale",
    "color": "Blanc ivoire",
    "notes": [
      "Caprin doux",
      "Crème",
      "Noisette",
      "Fleurs"
    ],
    "accords": {
      "vin": "Côtes du Forez blanc",
      "biere": "Blanche",
      "cidre": "Cidre sec",
      "whisky": "Lowlands",
      "pain": "Pain aux céréales"
    },
    "histoire": "Petit fromage de chèvre en forme de galet de rivière, de la plaine du Forez le long de la Loire.",
    "nutrition": {
      "energie": "300 kcal",
      "proteines": "18 g",
      "lipides": "25 g",
      "calcium": "150 mg"
    },
    "galerie": [
      "Galet",
      "Coupe",
      "Croûte",
      "Plateau",
      "Cave"
    ],
    "map": [
      60,
      60
    ],
    "regionId": "auvergne-rhone-alpes"
  },
  {
    "id": "pavin",
    "nom": "Pavin",
    "alt": [],
    "dept": "Puy-de-Dôme (63)",
    "commune": "Massif du Sancy (lac Pavin)",
    "lait": "Vache",
    "race": "Montbéliarde",
    "famille": "Pâte pressée non cuite",
    "croute": "Lavée, orangée",
    "texture": "Souple, crémeuse",
    "forme": "Dôme",
    "poids": "300–450 g",
    "dim": "Ø 10 cm",
    "affinage": "6 semaines",
    "mg": "45 %",
    "saison": "Toute l'année",
    "intensite": 2,
    "aop": false,
    "prix": "≈ 24 €/kg",
    "dispo": "Régionale",
    "color": "Ivoire",
    "notes": [
      "Doux",
      "Beurre",
      "Sous-bois"
    ],
    "accords": {
      "vin": "Côtes d'Auvergne",
      "biere": "Brune",
      "cidre": "Cidre brut",
      "whisky": "Highlands",
      "pain": "Pain de campagne"
    },
    "histoire": "Fromage à croûte lavée en forme de dôme, nommé d'après le lac Pavin, jeune fromage auvergnat moderne.",
    "nutrition": {
      "energie": "330 kcal",
      "proteines": "20 g",
      "lipides": "27 g",
      "calcium": "560 mg"
    },
    "galerie": [
      "Dôme",
      "Coupe",
      "Croûte lavée",
      "Plateau",
      "Cave"
    ],
    "map": [
      55,
      61
    ],
    "regionId": "auvergne-rhone-alpes"
  },
  {
    "id": "couronne-lozerienne",
    "nom": "Couronne lozérienne",
    "alt": [],
    "dept": "Lozère limitrophe / Haute-Loire (43)",
    "commune": "Aubrac-Margeride",
    "lait": "Vache",
    "race": "Aubrac",
    "famille": "Pâte pressée non cuite",
    "croute": "Naturelle",
    "texture": "Souple",
    "forme": "Couronne (anneau)",
    "poids": "1–1,5 kg",
    "dim": "Ø 20 cm",
    "affinage": "1–2 mois",
    "mg": "45 %",
    "saison": "Été",
    "intensite": 2,
    "aop": false,
    "prix": "≈ 26 €/kg",
    "dispo": "Rare",
    "color": "Ivoire",
    "notes": [
      "Doux",
      "Herbe",
      "Noisette"
    ],
    "accords": {
      "vin": "Marcillac",
      "biere": "Ambrée",
      "cidre": "Cidre brut",
      "whisky": "Highlands",
      "pain": "Pain de seigle"
    },
    "histoire": "Tomme en forme d'anneau des marges de l'Aubrac et de la Margeride, production fermière rare.",
    "nutrition": {
      "energie": "340 kcal",
      "proteines": "22 g",
      "lipides": "27 g",
      "calcium": "620 mg"
    },
    "galerie": [
      "Couronne",
      "Coupe",
      "Croûte",
      "Plateau",
      "Cave"
    ],
    "map": [
      54,
      66
    ],
    "regionId": "auvergne-rhone-alpes"
  },
  {
    "id": "margot",
    "nom": "Margot",
    "alt": [],
    "dept": "Loire (42)",
    "commune": "Région stéphanoise",
    "lait": "Vache",
    "race": "Montbéliarde",
    "famille": "Pâte molle à croûte fleurie",
    "croute": "Fine fleurie blanche",
    "texture": "Crémeuse, coulante",
    "forme": "Petit disque",
    "poids": "200 g",
    "dim": "Ø 9 cm",
    "affinage": "2–3 semaines",
    "mg": "55 %",
    "saison": "Toute l'année",
    "intensite": 2,
    "aop": false,
    "prix": "≈ 24 €/kg",
    "dispo": "Régionale",
    "color": "Ivoire",
    "notes": [
      "Crème",
      "Beurre",
      "Champignon",
      "Doux"
    ],
    "accords": {
      "vin": "Crémant, Côtes du Forez blanc",
      "biere": "Blanche",
      "cidre": "Cidre doux",
      "whisky": "Lowlands",
      "pain": "Baguette"
    },
    "histoire": "Fromage crémeux de la région du Forez, dans la lignée douce des pâtes molles à croûte fleurie.",
    "nutrition": {
      "energie": "340 kcal",
      "proteines": "15 g",
      "lipides": "30 g",
      "calcium": "300 mg"
    },
    "galerie": [
      "Disque",
      "Coupe",
      "Croûte",
      "Plateau",
      "Cave"
    ],
    "map": [
      60,
      59
    ],
    "regionId": "auvergne-rhone-alpes"
  }
]
