// GENERATED by scripts/enrich-wikipedia-extra.mjs — ne pas éditer à la main.
// Photos et résumés Wikipédia des fromages de cheeses-extra.ts, tenus à part
// pour que le fichier écrit à la main reste lisible. Recollés dans dataset.ts.
import type { CheeseImage, CheeseWikipedia } from './cheese.types'

export interface CheeseMedia {
  image?: CheeseImage
  wikipedia?: CheeseWikipedia
  galleryImages?: CheeseImage[]
}

export const EXTRA_MEDIA: Record<string, CheeseMedia> = {
  "tome-bauges": {
    "image": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Tome_des_Bauges.jpg/960px-Tome_des_Bauges.jpg",
      "width": 800,
      "height": 600,
      "credit": "Mit-Mit, Public domain",
      "creditUrl": "https://commons.wikimedia.org/wiki/File:Tome_des_Bauges.jpg"
    },
    "wikipedia": {
      "url": "https://fr.wikipedia.org/wiki/Tome_des_Bauges",
      "extract": "La tome des Bauges est un fromage au lait de vache produit en France. Elle doit son nom au mot \"toma\" qui signifie, en patois savoyard, \"fromage fabriqué dans les alpages\", ainsi qu'au lieu de sa fabrication le massif des Bauges. Il s'agit d'un fromage au lait cru entier ou partiellement écrémé, à pâte pressée non cuite, salée et à croûte fleurie de 18 à 20 cm de diamètre et 3 à 5 cm de hauteur pour 1,1 à 1,4 kg. Sa pâte est de couleur ivoire à jaune et sa croûte grise."
    },
    "galleryImages": [
      {
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Tome_des_Bauges.jpg/960px-Tome_des_Bauges.jpg",
        "width": 800,
        "height": 600,
        "credit": "Mit-Mit, Public domain",
        "creditUrl": "https://commons.wikimedia.org/wiki/File:Tome%20des%20Bauges.jpg"
      },
      {
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/.Tome_des_Bauges.jpg/960px-.Tome_des_Bauges.jpg",
        "width": 800,
        "height": 1191,
        "credit": "Marianne Casamance, CC BY-SA 4.0",
        "creditUrl": "https://commons.wikimedia.org/wiki/File:.Tome%20des%20Bauges.jpg"
      },
      {
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Abbaye_de_Tami%C3%A9_et_tome_des_Bauges.jpg/960px-Abbaye_de_Tami%C3%A9_et_tome_des_Bauges.jpg",
        "width": 800,
        "height": 533,
        "credit": "Nicolas Vigier from Paris, France, CC BY 2.0",
        "creditUrl": "https://commons.wikimedia.org/wiki/File:Abbaye%20de%20Tami%C3%A9%20et%20tome%20des%20Bauges.jpg"
      },
      {
        "url": "https://upload.wikimedia.org/wikipedia/commons/7/73/Matouille_Savoyarde.jpg",
        "width": 800,
        "height": 992,
        "credit": "Flaburgan, CC BY-SA 4.0",
        "creditUrl": "https://commons.wikimedia.org/wiki/File:Matouille%20Savoyarde.jpg"
      }
    ]
  },
  "emmental-savoie": {
    "image": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Emmental_de_Savoie_02.jpg/960px-Emmental_de_Savoie_02.jpg",
      "width": 800,
      "height": 533,
      "credit": "Pierre-Yves Beaudouin, CC BY-SA 4.0",
      "creditUrl": "https://commons.wikimedia.org/wiki/File:Emmental_de_Savoie_02.jpg"
    },
    "wikipedia": {
      "url": "https://fr.wikipedia.org/wiki/Emmental_de_Savoie",
      "extract": "L'emmental de Savoie est un fromage de vache au lait cru fabriqué en France dans les départements alpins de la Savoie et de la Haute-Savoie. Il fait partie de la famille des fromages à pâte pressée cuite. Le nom de ce fromage français est une indication géographique protégée. Il est parfois appelé à tort « gruyère »."
    },
    "galleryImages": [
      {
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Emmental_de_Savoie_01.jpg/960px-Emmental_de_Savoie_01.jpg",
        "width": 800,
        "height": 533,
        "credit": "Pierre-Yves Beaudouin, CC BY-SA 4.0",
        "creditUrl": "https://commons.wikimedia.org/wiki/File:Emmental%20de%20Savoie%2001.jpg"
      },
      {
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Emmental_de_Savoie_02.jpg/960px-Emmental_de_Savoie_02.jpg",
        "width": 800,
        "height": 533,
        "credit": "Pierre-Yves Beaudouin, CC BY-SA 4.0",
        "creditUrl": "https://commons.wikimedia.org/wiki/File:Emmental%20de%20Savoie%2002.jpg"
      },
      {
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Emmental_de_Savoie_03.jpg/960px-Emmental_de_Savoie_03.jpg",
        "width": 800,
        "height": 533,
        "credit": "Pierre-Yves Beaudouin, CC BY-SA 4.0",
        "creditUrl": "https://commons.wikimedia.org/wiki/File:Emmental%20de%20Savoie%2003.jpg"
      },
      {
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Emmental_de_Savoie_04.jpg/960px-Emmental_de_Savoie_04.jpg",
        "width": 800,
        "height": 533,
        "credit": "Pierre-Yves Beaudouin, CC BY-SA 4.0",
        "creditUrl": "https://commons.wikimedia.org/wiki/File:Emmental%20de%20Savoie%2004.jpg"
      }
    ]
  },
  "emmental-est-central": {
    "wikipedia": {
      "url": "https://fr.wikipedia.org/wiki/Emmental_fran%C3%A7ais_est-central",
      "extract": "L’emmental français est-central est un fromage de vache au lait cru produit en France dans une zone qui comprend la Franche-Comté, la Haute-Marne et les Vosges. Il fait partie de la famille des fromages à pâte pressée cuite. Le nom de ce fromage français est une indication géographique protégée et il bénéficie du Label Rouge."
    }
  },
  "ramequin": {
    "image": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Des_ramequins_%28fromage_de_Saint-Rambert-en-Bugey%29.jpg/960px-Des_ramequins_%28fromage_de_Saint-Rambert-en-Bugey%29.jpg",
      "width": 800,
      "height": 1067,
      "credit": "Classiccardinal, CC BY-SA 4.0",
      "creditUrl": "https://commons.wikimedia.org/wiki/File:Des_ramequins_(fromage_de_Saint-Rambert-en-Bugey).jpg"
    },
    "wikipedia": {
      "url": "https://fr.wikipedia.org/wiki/Ramequin_(fromage)",
      "extract": "Ramequin est une appellation désignant un fromage originaire du canton de Saint-Rambert-en-Bugey en France. Les ramequins élaborés dans le Bugey existent sous forme laitière, fabriquée à partir de lait pasteurisé, ou fermière, élaborée à partir de lait cru. Le ramequin désigne également le nom de la spécialité culinaire qui permet de le consommer sous la forme d'une fondue. Le ramequin est le plat convivial par excellence de la région montagneuse du Bugey, notamment au niveau de la vallée de l'A"
    },
    "galleryImages": [
      {
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Ramequin_%28cheese%29_-_1.jpg/960px-Ramequin_%28cheese%29_-_1.jpg",
        "width": 800,
        "height": 600,
        "credit": "Benoît Prieur, CC0",
        "creditUrl": "https://commons.wikimedia.org/wiki/File:Ramequin%20(cheese)%20-%201.jpg"
      },
      {
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Ramequin_%28cheese%29_-_2.jpg/960px-Ramequin_%28cheese%29_-_2.jpg",
        "width": 800,
        "height": 600,
        "credit": "Benoît Prieur, CC0",
        "creditUrl": "https://commons.wikimedia.org/wiki/File:Ramequin%20(cheese)%20-%202.jpg"
      },
      {
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Ramequin_-_3.jpg/960px-Ramequin_-_3.jpg",
        "width": 800,
        "height": 600,
        "credit": "Benoît Prieur, CC0",
        "creditUrl": "https://commons.wikimedia.org/wiki/File:Ramequin%20-%203.jpg"
      },
      {
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Ramequin_-_cheese_-_5.jpg/960px-Ramequin_-_cheese_-_5.jpg",
        "width": 800,
        "height": 600,
        "credit": "Benoît Prieur, CC0",
        "creditUrl": "https://commons.wikimedia.org/wiki/File:Ramequin%20-%20cheese%20-%205.jpg"
      }
    ]
  },
  "cervelle-canut": {
    "image": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Brasserie_Georges_-_cervelle_de_Canut.jpg/960px-Brasserie_Georges_-_cervelle_de_Canut.jpg",
      "width": 800,
      "height": 600,
      "credit": "Marianne Casamance, CC BY-SA 4.0",
      "creditUrl": "https://commons.wikimedia.org/wiki/File:Brasserie_Georges_-_cervelle_de_Canut.jpg"
    },
    "wikipedia": {
      "url": "https://fr.wikipedia.org/wiki/Cervelle_de_canut",
      "extract": "La cervelle de canut, également appelée claqueret ou tomme daubée, est une spécialité fromagère typique de la cuisine lyonnaise. Elle est dérivée d'une autre spécialité appelée sarasson."
    },
    "galleryImages": [
      {
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Brasserie_Georges_-_cervelle_de_Canut.jpg/960px-Brasserie_Georges_-_cervelle_de_Canut.jpg",
        "width": 800,
        "height": 600,
        "credit": "Marianne Casamance, CC BY-SA 4.0",
        "creditUrl": "https://commons.wikimedia.org/wiki/File:Brasserie%20Georges%20-%20cervelle%20de%20Canut.jpg"
      },
      {
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Cervelle_des_Canuts_servis_dans_le_Vieux_Lyon.jpg/960px-Cervelle_des_Canuts_servis_dans_le_Vieux_Lyon.jpg",
        "width": 800,
        "height": 538,
        "credit": "Jean-Marc ALBERT, CC BY-SA 3.0",
        "creditUrl": "https://commons.wikimedia.org/wiki/File:Cervelle%20des%20Canuts%20servis%20dans%20le%20Vieux%20Lyon.jpg"
      },
      {
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Plaque_rue_L%C3%A9on_de_Lyon_-_Paul_Lacombe_-_Cervelle_de_canut.JPG/960px-Plaque_rue_L%C3%A9on_de_Lyon_-_Paul_Lacombe_-_Cervelle_de_canut.JPG",
        "width": 800,
        "height": 600,
        "credit": "Benoît Prieur, CC0",
        "creditUrl": "https://commons.wikimedia.org/wiki/File:Plaque%20rue%20L%C3%A9on%20de%20Lyon%20-%20Paul%20Lacombe%20-%20Cervelle%20de%20canut.JPG"
      },
      {
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Saucisson_lyonnais_et_cervelle_de_canut_Aux_Gogniols_%28Lyon%29_ao%C3%BBt_2023.jpg/960px-Saucisson_lyonnais_et_cervelle_de_canut_Aux_Gogniols_%28Lyon%29_ao%C3%BBt_2023.jpg",
        "width": 800,
        "height": 600,
        "credit": "Benoît Prieur, CC0",
        "creditUrl": "https://commons.wikimedia.org/wiki/File:Saucisson%20lyonnais%20et%20cervelle%20de%20canut%20Aux%20Gogniols%20(Lyon)%20ao%C3%BBt%202023.jpg"
      }
    ]
  }
}
