// GENERATED by scripts/fetch-cheese-images.mjs from the Wikipedia / Wikimedia
// Commons APIs. Do not hand-edit — rerun the script to refresh.
//
// Empty until `npm run fetch-cheese-images` is run from an environment with
// outbound network access to *.wikipedia.org / *.wikimedia.org (this repo's
// sandboxed dev environment blocks those domains — see README).

export interface CheeseImage {
  /** Direct, hotlink-safe URL to a Wikimedia-hosted photo. */
  url: string
  width?: number
  height?: number
  /** Wikipedia article the photo was found on. */
  pageUrl: string
  /** Commons file page, when resolved — the canonical attribution target. */
  filePageUrl?: string
  /** Plain-text author/credit from the file's Commons metadata, if available. */
  author?: string
  license?: string
  licenseUrl?: string
}

/** Keyed by Cheese.id. Cheeses missing here fall back to the placeholder UI. */
export const CHEESE_IMAGES: Record<string, CheeseImage> = {}
