// GENERATED by scripts/import-cheeses.mjs from ../design_handoff_fromages_france/fr-map.js
// Real projected coordinates (viewBox 0 0 100 100) of each cheese on the
// metropolitan France outline, from Natural Earth data via d3-geo.
// Do not hand-edit — rerun the import script to regenerate.
export const FR_XY: Record<string, [number, number]> = {
  "reblochon": [
    73.45,
    54.17
  ],
  "beaufort": [
    75.22,
    55.61
  ],
  "bleu-auvergne": [
    50.11,
    61.28
  ],
  "saint-nectaire": [
    50.4,
    59.78
  ],
  "fourme-ambert": [
    55.82,
    58.56
  ],
  "cantal": [
    48.52,
    63.8
  ],
  "picodon": [
    64.36,
    66.51
  ],
  "mont-dor": [
    72.67,
    45.41
  ],
  "brillat-savarin": [
    65.49,
    51.58
  ],
  "rigotte-condrieu": [
    62.99,
    59.07
  ],
  "chevrotin": [
    74.41,
    54.19
  ],
  "abondance": [
    75.78,
    50.01
  ],
  "bleu-gex": [
    70.37,
    49.95
  ],
  "bleu-vercors": [
    67.66,
    63.32
  ],
  "bleu-causses": [
    51.96,
    73.08
  ],
  "laguiole": [
    49.98,
    67.41
  ],
  "salers": [
    47.38,
    62.95
  ],
  "raclette-savoie": [
    74.15,
    56.89
  ],
  "saint-marcellin": [
    67,
    61.78
  ],
  "saint-felicien": [
    64.81,
    62.52
  ],
  "tomme-savoie": [
    73.46,
    56.95
  ],
  "tomme-abondance": [
    75.78,
    50.01
  ],
  "tomme-tarentaise": [
    76.26,
    57.21
  ],
  "tomme-bauges": [
    72.24,
    56.45
  ],
  "tomme-belledonne": [
    71.96,
    60.04
  ],
  "tomme-chevre-vercors": [
    68.04,
    63.79
  ],
  "tomme-champsaur": [
    72.77,
    65.92
  ],
  "tomme-trieves": [
    69.52,
    64.88
  ],
  "tomme-champsaur2": [
    57.17,
    63.44
  ],
  "tommette-chevre-lyonnais": [
    60.99,
    56.81
  ],
  "charolais": [
    59.4,
    52.94
  ],
  "persille-aravis": [
    73.95,
    54.43
  ],
  "gaperon": [
    51.99,
    56.26
  ],
  "carre-aurillac": [
    47.02,
    65.04
  ],
  "pave-affinois": [
    62.39,
    59.5
  ],
  "fourme-montbrison": [
    58.01,
    57.96
  ],
  "comtomme": [
    68.43,
    54.35
  ],
  "serac": [
    74.15,
    56.89
  ],
  "vacherin-abondance": [
    75.78,
    50.01
  ],
  "vacherin-bauges": [
    72.24,
    56.45
  ],
  "bleu-thiezac": [
    48.67,
    64.1
  ],
  "bleu-laqueuille": [
    48.94,
    57.86
  ],
  "murol": [
    50.29,
    58.6
  ],
  "rochebaron": [
    58.44,
    60.91
  ],
  "bouton-culotte": [
    61.33,
    50.85
  ],
  "claousou": [
    54.49,
    66.04
  ],
  "galet-loire": [
    58.23,
    56.96
  ],
  "pavin": [
    50.03,
    59.3
  ],
  "couronne-lozerienne": [
    53.13,
    67.09
  ],
  "margot": [
    60.44,
    59.32
  ]
}
